# Generated by Django 3.2.13 on 2022-11-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trasferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, verbose_name='Documeto')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('unidades', models.IntegerField(verbose_name='Unidades')),
            ],
        ),
    ]
