# Generated by Django 3.2.13 on 2022-11-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('propietario', models.CharField(blank=True, default='Gimpromed. Cia. Ltda.', max_length=50, verbose_name='Propietario')),
                ('docuemento', models.CharField(choices=[('Electrónico', 'Electrónico'), ('Fisíco', 'Fisíco')], max_length=50, verbose_name='Documento')),
                ('registro', models.CharField(max_length=50, verbose_name='Reg. Sanitario')),
                ('producto', models.TextField(blank=True, verbose_name='Producto Denominado')),
                ('origen', models.CharField(blank=True, max_length=50, verbose_name='Origen Fabricante')),
                ('imp_desde', models.CharField(blank=True, max_length=50, verbose_name='Importado desde')),
                ('fecha_expedicion', models.DateField(blank=True, null=True, verbose_name='Fecha de expedición')),
                ('fecha_expiracion', models.DateField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('lugar_archivo', models.CharField(blank=True, max_length=50, verbose_name='Importado desde')),
                ('cn_recomen', models.IntegerField(blank=True, default=0, null=True, verbose_name='Copias Notariadas Recomendadas')),
                ('cn_carpeta', models.IntegerField(blank=True, default=0, null=True, verbose_name='Copias Notariadas Carpeta')),
                ('fecha_notaria', models.DateField(blank=True, null=True, verbose_name='Fecha de envio a notaria')),
                ('notaria', models.CharField(blank=True, max_length=50, verbose_name='Notaria')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('n_solicitud', models.CharField(blank=True, max_length=50, verbose_name='Número Solicitud')),
                ('n_emision', models.CharField(blank=True, max_length=50, verbose_name='Número de emisión')),
                ('observacion', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
        ),
    ]
