# Generated by Django 3.2.13 on 2022-11-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0002_registrosanitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrosanitario',
            old_name='docuemento',
            new_name='documento',
        ),
    ]
