# Generated by Django 3.2.13 on 2022-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0003_rename_docuemento_registrosanitario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosanitario',
            name='documento',
            field=models.CharField(choices=[('Electrónico', 'Electrónico'), ('Fisíco', 'Fisíco')], default='Electrónico', max_length=50, verbose_name='Documento'),
        ),
    ]
