# Generated by Django 3.2.13 on 2023-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0006_importacionesexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionesexcel',
            name='excel',
            field=models.FileField(upload_to='excel_importacion', verbose_name='Archivo Excel'),
        ),
        migrations.AlterField(
            model_name='importacionesexcel',
            name='marca',
            field=models.CharField(max_length=150, verbose_name='Marca ó Proveedor'),
        ),
        migrations.AlterField(
            model_name='importacionesexcel',
            name='orden_importacion',
            field=models.CharField(max_length=150, verbose_name='Número de Orden/Importación'),
        ),
    ]
