# Generated by Django 3.2.13 on 2024-06-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0008_registrosanitario_activo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportacionesExcel',
        ),
    ]
