# Generated by Django 3.2.13 on 2024-07-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0009_delete_importacionesexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosanitario',
            name='cn_carpeta',
            field=models.IntegerField(default=0, verbose_name='Copias Notariadas Carpeta'),
        ),
        migrations.AlterField(
            model_name='registrosanitario',
            name='cn_recomen',
            field=models.IntegerField(default=0, verbose_name='Copias Notariadas Recomendadas'),
        ),
    ]
