# Generated by Django 5.1.4 on 2025-01-14 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpa', '0010_auto_20240726_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasferencia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
