# Generated by Django 3.2.13 on 2022-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product name')),
                ('group_code', models.CharField(max_length=50, verbose_name='Group code')),
                ('um', models.CharField(max_length=50, verbose_name='Presentación')),
                ('oh', models.IntegerField(verbose_name='OH')),
                ('oh2', models.IntegerField(verbose_name='OH2')),
                ('commited', models.IntegerField(verbose_name='Commited')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('lote_id', models.CharField(max_length=50, verbose_name='Lote')),
                ('fecha_elab_lote', models.CharField(max_length=10, verbose_name='Fecha elaboración lote')),
                ('fecha_cadu_lote', models.CharField(max_length=10, verbose_name='Fecha caducidad lote')),
                ('ware_code', models.CharField(max_length=10, verbose_name='Bodega')),
                ('location', models.CharField(max_length=10, verbose_name='Ubicación')),
                ('unidades_caja', models.IntegerField(blank=True, verbose_name='Unidades por caja')),
                ('numero_cajas', models.IntegerField(blank=True, verbose_name='Número de cajas')),
                ('unidades_sueltas', models.IntegerField(blank=True, verbose_name='Unidades sueltas')),
                ('total_unidades', models.IntegerField(blank=True, verbose_name='Total de unidades')),
                ('diferencia', models.IntegerField(blank=True, verbose_name='Diferencia')),
                ('observaciones', models.CharField(blank=True, max_length=100, verbose_name='Observaciones')),
            ],
        ),
    ]
