# Generated by Django 3.2.13 on 2022-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha_cadu_lote',
            field=models.DateField(verbose_name='Fecha caducidad lote'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_elab_lote',
            field=models.DateField(verbose_name='Fecha elaboración lote'),
        ),
    ]
