# Generated by Django 3.2.13 on 2022-10-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20221025_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='llenado',
            field=models.BooleanField(default=False, verbose_name='Toma de inventario'),
        ),
    ]
