# Generated by Django 3.2.13 on 2022-11-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_llenado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='agregado',
            field=models.BooleanField(default=False, verbose_name='Añadido'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='commited',
            field=models.IntegerField(blank=True, verbose_name='Commited'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_cadu_lote',
            field=models.DateField(blank=True, verbose_name='Fecha caducidad lote'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_elab_lote',
            field=models.DateField(blank=True, verbose_name='Fecha elaboración lote'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='group_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Group code'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='location',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='lote_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='oh',
            field=models.IntegerField(blank=True, verbose_name='OH'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='oh2',
            field=models.IntegerField(blank=True, verbose_name='OH2'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='um',
            field=models.CharField(blank=True, max_length=50, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ware_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Bodega'),
        ),
    ]
