# Generated by Django 3.2.13 on 2022-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_inventario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='llenado',
            field=models.BooleanField(default=False, verbose_name='Llenado'),
        ),
    ]
