# Generated by Django 3.2.13 on 2022-12-14 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_alter_inventario_llenado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='InventarioTotale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50, verbose_name='Product id')),
                ('ware_code', models.CharField(blank=True, max_length=10, verbose_name='Bodega')),
                ('location', models.CharField(blank=True, max_length=10, verbose_name='Ubicación')),
                ('unidades_caja', models.IntegerField(blank=True, verbose_name='Unidades por caja')),
                ('numero_cajas', models.IntegerField(blank=True, verbose_name='Número de cajas')),
                ('unidades_sueltas', models.IntegerField(blank=True, verbose_name='Unidades sueltas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
