# Generated by Django 3.2.13 on 2022-12-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20221214_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariototale',
            old_name='location',
            new_name='location_t',
        ),
        migrations.RenameField(
            model_name='inventariototale',
            old_name='numero_cajas',
            new_name='numero_cajas_t',
        ),
        migrations.RenameField(
            model_name='inventariototale',
            old_name='product_id',
            new_name='product_id_t',
        ),
        migrations.RenameField(
            model_name='inventariototale',
            old_name='unidades_caja',
            new_name='unidades_caja_t',
        ),
        migrations.RenameField(
            model_name='inventariototale',
            old_name='unidades_sueltas',
            new_name='unidades_sueltas_t',
        ),
        migrations.RenameField(
            model_name='inventariototale',
            old_name='ware_code',
            new_name='ware_code_t',
        ),
    ]
