# Generated by Django 3.2.13 on 2022-12-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20221214_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariototale',
            name='total_unidades_t',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de unidades'),
        ),
    ]
