# Generated by Django 3.2.13 on 2023-06-22 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos', '0022_timestamp_actualization_reserva_lote'),
        ('inventario', '0009_inventariototale_total_unidades_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('productos', models.ManyToManyField(blank=True, to='datos.Product', verbose_name='Productos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
