# Generated by Django 3.2.13 on 2023-06-23 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0010_arqueo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_arqueo', models.IntegerField(blank=True, verbose_name='Arqueo')),
                ('product_id', models.CharField(blank=True, max_length=50, verbose_name='Product id')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Product name')),
                ('group_code', models.CharField(blank=True, max_length=50, verbose_name='Group code')),
                ('um', models.CharField(blank=True, max_length=50, verbose_name='Presentación')),
                ('oh', models.IntegerField(blank=True, verbose_name='OH')),
                ('oh2', models.IntegerField(blank=True, verbose_name='OH2')),
                ('commited', models.IntegerField(blank=True, verbose_name='Commited')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Quantity')),
                ('lote_id', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('fecha_elab_lote', models.DateField(blank=True, verbose_name='Fecha elaboración lote')),
                ('fecha_cadu_lote', models.DateField(blank=True, verbose_name='Fecha caducidad lote')),
                ('ware_code', models.CharField(blank=True, max_length=10, verbose_name='Bodega')),
                ('location', models.CharField(blank=True, max_length=10, verbose_name='Ubicación')),
                ('unidades_caja', models.IntegerField(blank=True, verbose_name='Unidades por caja')),
                ('numero_cajas', models.IntegerField(blank=True, verbose_name='Número de cajas')),
                ('unidades_sueltas', models.IntegerField(blank=True, verbose_name='Unidades sueltas')),
                ('total_unidades', models.IntegerField(blank=True, verbose_name='Total de unidades')),
                ('diferencia', models.IntegerField(blank=True, verbose_name='Diferencia')),
                ('observaciones', models.CharField(blank=True, max_length=100, verbose_name='Observaciones')),
                ('llenado', models.BooleanField(default=False, verbose_name='Llenado')),
                ('agregado', models.BooleanField(default=False, verbose_name='Añadido')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
