# Generated by Django 3.2.13 on 2023-06-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_arqueofisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueofisico',
            name='diferencia',
            field=models.IntegerField(blank=True, default=0, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='arqueofisico',
            name='numero_cajas',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número de cajas'),
        ),
        migrations.AlterField(
            model_name='arqueofisico',
            name='total_unidades',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total de unidades'),
        ),
        migrations.AlterField(
            model_name='arqueofisico',
            name='unidades_caja',
            field=models.IntegerField(blank=True, default=0, verbose_name='Unidades por caja'),
        ),
        migrations.AlterField(
            model_name='arqueofisico',
            name='unidades_sueltas',
            field=models.IntegerField(blank=True, default=0, verbose_name='Unidades sueltas'),
        ),
    ]
