# Generated by Django 3.2.13 on 2023-06-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_arqueoscreados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueoscreados',
            name='arqueo_id',
        ),
        migrations.AddField(
            model_name='arqueoscreados',
            name='arqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.arqueo', verbose_name='Arqueo'),
        ),
        migrations.AddField(
            model_name='arqueoscreados',
            name='ware_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bodega código'),
        ),
    ]
