# Generated by Django 3.2.13 on 2023-06-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20230626_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueoscreados',
            name='fecha_hora_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
