# Generated by Django 3.2.13 on 2023-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_arqueoscreados_fecha_hora_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueoscreados',
            name='reservas',
            field=models.TextField(blank=True, verbose_name='Reservas'),
        ),
    ]
