# Generated by Django 3.2.13 on 2023-07-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_arqueo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueo',
            name='usuario',
        ),
    ]
