# Generated by Django 3.2.13 on 2023-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0023_timestamp_actualization_imp_llegadas'),
        ('inventario', '0020_arqueo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arqueo',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='datos.Product', verbose_name='Productos'),
        ),
    ]
