# Generated by Django 3.2.13 on 2023-07-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_alter_arqueoscreados_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueoscreados',
            name='arqueo',
        ),
    ]
