# Generated by Django 3.2.13 on 2023-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_arqueofisico_observaciones2'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueoscreados',
            name='reservas_sinlote',
            field=models.TextField(blank=True, verbose_name='Reservas sin lote'),
        ),
    ]
