# Generated by Django 3.2.25 on 2024-12-10 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0030_inventariocerezos'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioCerezosTotale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_t', models.CharField(blank=True, max_length=50, verbose_name='Product id')),
                ('ware_code_t', models.CharField(blank=True, max_length=10, verbose_name='Bodega')),
                ('location_t', models.CharField(blank=True, max_length=10, verbose_name='Ubicación')),
                ('unidades_caja_t', models.IntegerField(blank=True, verbose_name='Unidades por caja')),
                ('numero_cajas_t', models.IntegerField(blank=True, verbose_name='Número de cajas')),
                ('unidades_sueltas_t', models.IntegerField(blank=True, verbose_name='Unidades sueltas')),
                ('total_unidades_t', models.IntegerField(blank=True, null=True, verbose_name='Total de unidades')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
