# Generated by Django 3.2.25 on 2024-12-12 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0065_ordenempaque_archivo'),
        ('inventario', '0031_inventariocerezostotale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariocerezostotale',
            name='location_t',
        ),
        migrations.RemoveField(
            model_name='inventariocerezostotale',
            name='ware_code_t',
        ),
        migrations.AddField(
            model_name='inventariocerezostotale',
            name='ubicacion',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_totales_ubicacion', to='wms.ubicacion', verbose_name='Ubicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='numero_cajas_t',
            field=models.IntegerField(default=0, verbose_name='Número de cajas'),
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='product_id_t',
            field=models.CharField(max_length=50, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='total_unidades_t',
            field=models.IntegerField(default=0, verbose_name='Total de unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='unidades_caja_t',
            field=models.IntegerField(default=0, verbose_name='Unidades por caja'),
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='unidades_sueltas_t',
            field=models.IntegerField(default=0, verbose_name='Unidades sueltas'),
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
    ]
