# Generated by Django 3.2.25 on 2024-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_auto_20241212_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='total_unidades_t',
            field=models.IntegerField(default=0, verbose_name='Total de unidades'),
        ),
    ]
