# Generated by Django 3.2.25 on 2024-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0033_alter_inventariocerezostotale_total_unidades_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='total_unidades_t',
            field=models.IntegerField(blank=True, verbose_name='Total de unidades'),
        ),
    ]
