# Generated by Django 3.2.25 on 2024-12-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0034_alter_inventariocerezostotale_total_unidades_t'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='numero_cajas_t',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número de cajas'),
        ),
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='unidades_sueltas_t',
            field=models.IntegerField(blank=True, default=0, verbose_name='Unidades sueltas'),
        ),
    ]
