# Generated by Django 3.2.25 on 2024-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_auto_20241212_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariocerezostotale',
            name='unidades_caja_t',
            field=models.IntegerField(verbose_name='Unidades por caja'),
        ),
        migrations.AlterField(
            model_name='inventariototale',
            name='location_t',
            field=models.CharField(max_length=10, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='inventariototale',
            name='product_id_t',
            field=models.CharField(max_length=50, verbose_name='Product id'),
        ),
        migrations.AlterField(
            model_name='inventariototale',
            name='ware_code_t',
            field=models.CharField(max_length=10, verbose_name='Bodega'),
        ),
    ]
