# Generated by Django 5.1.4 on 2025-06-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0036_auto_20241212_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='unidades_estanteria',
            field=models.IntegerField(blank=True, default=0, verbose_name='Unidades estanteria'),
            preserve_default=False,
        ),
    ]
