# Generated by Django 5.1.4 on 2025-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_inventario_unidades_estanteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='llenado_estanteria',
            field=models.BooleanField(default=False, verbose_name='Llenado estanteria'),
        ),
    ]
