# Generated by Django 5.1.4 on 2025-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_inventario_llenado_estanteria'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventariototale',
            unique_together={('product_id_t', 'ware_code_t', 'location_t')},
        ),
    ]
