# Generated by Django 3.2.13 on 2023-03-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperfil',
            name='firma_carta',
            field=models.CharField(blank=True, max_length=40, verbose_name='Firma Carta'),
        ),
        migrations.AddField(
            model_name='userperfil',
            name='posicion_carta',
            field=models.CharField(blank=True, max_length=40, verbose_name='Posición Carta'),
        ),
    ]
