# Generated by Django 3.2.13 on 2023-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionprocesos',
            name='mes',
            field=models.DateField(blank=True, verbose_name='Fecha'),
        ),
    ]
