# Generated by Django 3.2.13 on 2023-02-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0002_alter_evaluacionprocesos_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionprocesos',
            old_name='mes',
            new_name='fecha',
        ),
    ]
