# Generated by Django 3.2.13 on 2023-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0003_rename_mes_evaluacionprocesos_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionprocesos',
            name='insumos_participantes',
            field=models.TextField(blank=True, verbose_name='Insumos participantes'),
        ),
    ]
