# Generated by Django 3.2.13 on 2023-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0005_alter_evaluacionprocesos_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesosSercop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=100, unique=True, verbose_name='Poroceso')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora')),
            ],
        ),
    ]
