# Generated by Django 3.2.13 on 2024-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0006_procesossercop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=15, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nombre_generico', models.CharField(blank=True, max_length=150, verbose_name='Nombre generico')),
                ('presentacion', models.CharField(blank=True, max_length=15, verbose_name='Presentación')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('procedencia', models.CharField(blank=True, max_length=50, verbose_name='Procedencia')),
                ('r_sanitario', models.CharField(blank=True, max_length=50, verbose_name='Registro Sanitario')),
                ('lote_id', models.CharField(max_length=15, verbose_name='Código')),
                ('f_elaboracion', models.DateField(blank=True, verbose_name='Fecha elaboración')),
                ('f_caducidad', models.DateField(blank=True, verbose_name='Fecha caducidad')),
                ('cantidad', models.IntegerField(blank=True, verbose_name='Cantidad')),
                ('cantidad_total', models.IntegerField(blank=True, verbose_name='Cantidad total')),
                ('precio_unitario', models.FloatField(blank=True, verbose_name='Precio unitario')),
                ('precio_total', models.FloatField(blank=True, verbose_name='Precio total')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pedido', models.CharField(max_length=10, verbose_name='Picking')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('direccion', models.CharField(blank=True, max_length=150, verbose_name='Dirección')),
                ('orden_compra', models.CharField(blank=True, max_length=50, verbose_name='Orden de compra')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('productos', models.ManyToManyField(to='compras_publicas.ProductAnexo')),
            ],
        ),
    ]
