# Generated by Django 3.2.13 on 2024-06-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0007_anexo_productanexo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAnexo',
            new_name='Producto',
        ),
    ]
