# Generated by Django 3.2.13 on 2024-06-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0008_rename_productanexo_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexo',
            old_name='productos',
            new_name='product_list',
        ),
    ]
