# Generated by Django 3.2.13 on 2024-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0009_rename_productos_anexo_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad_total',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lote_id',
            field=models.CharField(max_length=15, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_total',
            field=models.FloatField(blank=True, default=0, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.FloatField(blank=True, default=0, verbose_name='Precio unitario'),
        ),
    ]
