# Generated by Django 3.2.13 on 2024-06-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0010_auto_20240605_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='n_factura',
            field=models.CharField(blank=True, default='001-001-0000', max_length=50, verbose_name='Factura'),
        ),
    ]
