# Generated by Django 3.2.13 on 2024-06-19 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0011_anexo_n_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Hora'),
            preserve_default=False,
        ),
    ]
