# Generated by Django 3.2.13 on 2024-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0012_anexo_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='fecha_formato',
            field=models.CharField(blank=True, choices=[('Y-m-d', 'aaaa-mm-dd Ej: 2024-12-31'), ('Y-m', 'aaaa-mm Ej: 2024-12'), ('d-m-Y', 'dd-mm-aaaa Ej: 31-12-2024'), ('m-Y', 'mm-aaaa Ej: 12-2024'), ('Y/m/d', 'aaaa/mm/dd Ej: 2024/12/31'), ('Y/m', 'aaaa/mm Ej: 2024/12'), ('d/m/Y', 'dd/mm/aaaa Ej: 2024/12/31'), ('m/Y', 'mm/aaaa Ej: 12/2024')], max_length=50, verbose_name='Formato de fecha'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='n_autorizacion',
            field=models.CharField(blank=True, max_length=150, verbose_name='N autorización'),
        ),
    ]
