# Generated by Django 3.2.13 on 2024-06-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0014_alter_anexo_fecha_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_formato',
            field=models.CharField(blank=True, default='Y-m-d', max_length=20, verbose_name='Formato de Fecha'),
        ),
    ]
