# Generated by Django 3.2.13 on 2024-06-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0015_producto_fecha_formato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='fecha_formato',
        ),
        migrations.AddField(
            model_name='anexo',
            name='ff_key',
            field=models.CharField(blank=True, default='aaaa-mm-dd', max_length=50, verbose_name='Formato de fecha'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='ff_value',
            field=models.CharField(blank=True, default='Y-m-d', max_length=50, verbose_name='Formato de fecha'),
        ),
    ]
