# Generated by Django 3.2.13 on 2024-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0018_anexo_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='iva',
            field=models.FloatField(blank=True, default=15, verbose_name='IVA'),
        ),
    ]
