# Generated by Django 3.2.13 on 2024-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0019_alter_anexo_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='dd_key',
            field=models.CharField(blank=True, default='0.00', max_length=50, verbose_name='Formato de decimal'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='dd_value',
            field=models.IntegerField(blank=True, default=2, verbose_name='Formato de decimal'),
        ),
    ]
