# Generated by Django 3.2.13 on 2024-08-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0021_producto_decimal_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesossercop',
            name='estado_participacion',
            field=models.CharField(blank=True, choices=[('GANADO', 'GANADO'), ('PERDIDO', 'PERDIDO'), ('NO CALIFICADO', 'NO CALIFICADO'), ('OTRO', 'OTRO'), ('NO PARTICIPADO', 'NO PARTICIPADO')], max_length=20),
        ),
        migrations.AddField(
            model_name='procesossercop',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='procesossercop',
            name='participa',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=10),
        ),
    ]
