# Generated by Django 3.2.13 on 2024-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0022_auto_20240822_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=40, verbose_name='Presentación'),
        ),
    ]
