# Generated by Django 3.2.13 on 2024-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0023_alter_producto_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesossercop',
            name='proceso',
            field=models.CharField(max_length=100, unique=True, verbose_name='Procesos'),
        ),
    ]
