# Generated by Django 3.2.25 on 2024-11-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0024_alter_procesossercop_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_id',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
