# Generated by Django 5.1.4 on 2025-01-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0025_alter_producto_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesossercop',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
