# Generated by Django 5.1.4 on 2025-04-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_publicas', '0026_procesossercop_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(blank=True, default=1, verbose_name='Orden'),
        ),
    ]
