# Generated by Django 5.1.4 on 2026-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.CharField(db_column='CODIGO_CLIENTE', max_length=100, primary_key=True, serialize=False)),
                ('identificacion_fiscal', models.CharField(db_column='IDENTIFICACION_FISCAL', max_length=100)),
                ('nombre_cliente', models.CharField(db_column='NOMBRE_CLIENTE', max_length=200)),
                ('ciudad_principal', models.CharField(blank=True, db_column='CIUDAD_PRINCIPAL', max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, db_column='CLIENT_TYPE', max_length=50, null=True)),
                ('salesman', models.CharField(blank=True, db_column='SALESMAN', max_length=50, null=True)),
                ('limite_credito', models.IntegerField(blank=True, db_column='LIMITE_CREDITO', null=True)),
                ('pricelist', models.IntegerField(blank=True, db_column='PRICELIST', null=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=200, null=True)),
                ('email_fiscal', models.EmailField(blank=True, db_column='Email_Fiscal', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=200, null=True)),
                ('wp', models.CharField(blank=True, db_column='WP', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True)),
                ('marca_det', models.CharField(blank=True, db_column='MarcaDet', max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, db_column='Unidad', max_length=45, null=True)),
                ('unidad_empaque', models.IntegerField(blank=True, db_column='Unidad_Empaque', null=True)),
                ('reg_san', models.CharField(blank=True, db_column='Reg_San', max_length=100, null=True)),
                ('procedencia', models.CharField(blank=True, db_column='Procedencia', max_length=100, null=True)),
                ('unidad_box', models.CharField(blank=True, db_column='Unidad_Box', max_length=45, null=True)),
                ('inactivo', models.IntegerField(blank=True, db_column='Inactivo', null=True)),
                ('largo', models.FloatField(blank=True, db_column='Largo', null=True)),
                ('ancho', models.FloatField(blank=True, db_column='Ancho', null=True)),
                ('altura', models.FloatField(blank=True, db_column='Altura', null=True)),
                ('volumen', models.FloatField(blank=True, db_column='Volumen', null=True)),
                ('peso', models.FloatField(blank=True, db_column='Peso', null=True)),
                ('disponible', models.IntegerField(blank=True, db_column='Disponible', null=True)),
                ('unidades_por_pallet', models.IntegerField(blank=True, db_column='UnidadesPorPallet', null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('unique_id', models.IntegerField(db_column='UNIQUE_ID', primary_key=True, serialize=False)),
                ('contrato_id', models.CharField(db_column='CONTRATO_ID', max_length=100)),
                ('fecha_pedido', models.DateField(db_column='FECHA_PEDIDO')),
                ('codigo_cliente', models.CharField(db_column='CODIGO_CLIENTE', max_length=100)),
                ('nombre_cliente', models.CharField(db_column='NOMBRE_CLIENTE', max_length=200)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=100)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=200)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('despachados', models.IntegerField(blank=True, db_column='Despachados', null=True)),
                ('ware_code', models.CharField(blank=True, db_column='WARE_CODE', max_length=20, null=True)),
                ('confirmed', models.IntegerField(blank=True, db_column='CONFIRMED', null=True)),
                ('hora_llegada', models.TimeField(blank=True, db_column='HORA_LLEGADA', null=True)),
                ('sec_name_cliente', models.CharField(blank=True, db_column='SEC_NAME_CLIENTE', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'managed': False,
            },
        ),
    ]
