# Generated by Django 5.1.4 on 2026-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0002_delete_cliente_delete_producto_delete_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.CharField(db_column='CODIGO_CLIENTE', max_length=100, primary_key=True, serialize=False)),
                ('identificacion_fiscal', models.CharField(db_column='IDENTIFICACION_FISCAL', max_length=100)),
                ('nombre_cliente', models.CharField(db_column='NOMBRE_CLIENTE', max_length=200)),
                ('ciudad_principal', models.CharField(blank=True, db_column='CIUDAD_PRINCIPAL', max_length=100, null=True)),
                ('client_type', models.CharField(blank=True, db_column='CLIENT_TYPE', max_length=50, null=True)),
                ('salesman', models.CharField(blank=True, db_column='SALESMAN', max_length=50, null=True)),
                ('limite_credito', models.IntegerField(blank=True, db_column='LIMITE_CREDITO', null=True)),
                ('pricelist', models.IntegerField(blank=True, db_column='PRICELIST', null=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=200, null=True)),
                ('email_fiscal', models.EmailField(blank=True, db_column='Email_Fiscal', max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=200, null=True)),
                ('wp', models.CharField(blank=True, db_column='WP', max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentasCobrar',
            fields=[
                ('codigo_factura', models.CharField(db_column='CODIGO_FACTURA', max_length=255, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, db_column='NUMERO_FACTURA', max_length=50, null=True)),
                ('codigo_cliente', models.CharField(blank=True, db_column='CODIGO_CLIENTE', max_length=50, null=True)),
                ('identificacion_fiscal', models.CharField(blank=True, db_column='IDENTIFICACION_FISCAL', max_length=20, null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='NOMBRE_CLIENTE', max_length=255, null=True)),
                ('fecha_factura', models.DateField(blank=True, db_column='FECHA_FACTURA', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='FECHA_VENCIMIENTO', null=True)),
                ('valor_total_pagado', models.DecimalField(blank=True, db_column='VALOR_TOTAL_PAGADO', decimal_places=2, max_digits=15, null=True)),
                ('valor_total_saldo_a_cobrar', models.DecimalField(blank=True, db_column='VALOR_TOTAL_SALDO_A_COBRAR', decimal_places=2, max_digits=15, null=True)),
                ('balance', models.DecimalField(blank=True, db_column='BALANCE', decimal_places=2, max_digits=15, null=True)),
                ('en_estatus_no_venta_b', models.BooleanField(blank=True, db_column='EN_ESTATUS_NO_VENTA_B', null=True)),
                ('limite_credito', models.DecimalField(blank=True, db_column='LIMITE_CREDITO', decimal_places=2, max_digits=15, null=True)),
                ('price_list', models.CharField(blank=True, db_column='PriceList', max_length=50, null=True)),
                ('salesman', models.CharField(blank=True, db_column='SALESMAN', max_length=100, null=True)),
                ('riesgo', models.CharField(blank=True, db_column='RIESGO', max_length=50, null=True)),
                ('terminos_de_pago_alfa_num', models.CharField(blank=True, db_column='TERMINOS_DE_PAGO_ALFA_NUM', max_length=50, null=True)),
                ('terminos_de_pago_dias', models.IntegerField(blank=True, db_column='TERMINOS_DE_PAGO_DIAS', null=True)),
                ('dias_ven', models.IntegerField(blank=True, db_column='DIAS_VEN', null=True)),
                ('categoria_mora', models.CharField(blank=True, db_column='CATEGORIA_MORA', max_length=90, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'db_table': 'cuentas_cobrar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=100, null=True)),
                ('marca_det', models.CharField(blank=True, db_column='MarcaDet', max_length=200, null=True)),
                ('unidad', models.CharField(blank=True, db_column='Unidad', max_length=45, null=True)),
                ('unidad_empaque', models.IntegerField(blank=True, db_column='Unidad_Empaque', null=True)),
                ('reg_san', models.CharField(blank=True, db_column='Reg_San', max_length=100, null=True)),
                ('procedencia', models.CharField(blank=True, db_column='Procedencia', max_length=100, null=True)),
                ('unidad_box', models.CharField(blank=True, db_column='Unidad_Box', max_length=45, null=True)),
                ('inactivo', models.IntegerField(blank=True, db_column='Inactivo', null=True)),
                ('largo', models.FloatField(blank=True, db_column='Largo', null=True)),
                ('ancho', models.FloatField(blank=True, db_column='Ancho', null=True)),
                ('altura', models.FloatField(blank=True, db_column='Altura', null=True)),
                ('volumen', models.FloatField(blank=True, db_column='Volumen', null=True)),
                ('peso', models.FloatField(blank=True, db_column='Peso', null=True)),
                ('disponible', models.IntegerField(blank=True, db_column='Disponible', null=True)),
                ('unidades_por_pallet', models.IntegerField(blank=True, db_column='UnidadesPorPallet', null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('ref', models.CharField(db_column='Ref', max_length=45, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, db_column='Detalle', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=45, null=True)),
                ('precio_h', models.FloatField(blank=True, db_column='PrecioH', null=True)),
                ('precio_d', models.FloatField(blank=True, db_column='PrecioD', null=True)),
                ('promocion', models.CharField(blank=True, db_column='Promocion', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('unique_id', models.IntegerField(db_column='UNIQUE_ID', primary_key=True, serialize=False)),
                ('contrato_id', models.CharField(db_column='CONTRATO_ID', max_length=100)),
                ('fecha_pedido', models.DateField(db_column='FECHA_PEDIDO')),
                ('codigo_cliente', models.CharField(db_column='CODIGO_CLIENTE', max_length=100)),
                ('nombre_cliente', models.CharField(db_column='NOMBRE_CLIENTE', max_length=200)),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=100)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=200)),
                ('quantity', models.IntegerField(db_column='QUANTITY')),
                ('despachados', models.IntegerField(blank=True, db_column='Despachados', null=True)),
                ('ware_code', models.CharField(blank=True, db_column='WARE_CODE', max_length=20, null=True)),
                ('confirmed', models.IntegerField(blank=True, db_column='CONFIRMED', null=True)),
                ('hora_llegada', models.TimeField(blank=True, db_column='HORA_LLEGADA', null=True)),
                ('sec_name_cliente', models.CharField(blank=True, db_column='SEC_NAME_CLIENTE', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'managed': False,
            },
        ),
    ]
