# Generated by Django 5.1.4 on 2026-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorMBA',
            fields=[
                ('code', models.CharField(db_column='CODE', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
                'managed': False,
            },
        ),
    ]
