# Generated by Django 5.1.4 on 2026-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_vendedormba'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisABC',
            fields=[
                ('product_id', models.CharField(db_column='Product_id', max_length=100, primary_key=True, serialize=False)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
                ('f_relativa', models.FloatField(blank=True, db_column='F_relativa', null=True)),
                ('f_acumulada', models.FloatField(blank=True, db_column='F_acumulada', null=True)),
            ],
            options={
                'verbose_name': 'Análisis ABC',
                'verbose_name_plural': 'Análisis ABC',
                'db_table': 'analisis_abc',
                'managed': False,
            },
        ),
    ]
