# Generated by Django 3.2.13 on 2023-05-15 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioIngresoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_compra', models.CharField(max_length=50, verbose_name='Orden de compra')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('marca2', models.CharField(blank=True, max_length=50, verbose_name='Marca 2')),
                ('lote_id', models.CharField(max_length=50, verbose_name='Lote id')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('bodega', models.CharField(max_length=5, verbose_name='Bodega')),
                ('unidades_ingresadas', models.IntegerField(verbose_name='Unidades ingresadas')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7')], max_length=10, verbose_name='Bodega')),
                ('pasillo', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=10, verbose_name='Pasillo')),
                ('modulo', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09')], max_length=10, verbose_name='Modulo')),
                ('nivel', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06')], max_length=10, verbose_name='Nivel')),
                ('capacidad_m3', models.FloatField(verbose_name='Capacidad m3')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento')),
                ('unidades', models.IntegerField(verbose_name='Unidades ingresadas')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='wms.inventarioingresobodega', verbose_name='Item')),
                ('ubicacion', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.PROTECT, related_name='ubicacion', to='wms.ubicacion', verbose_name='Ubicación')),
            ],
        ),
    ]
