# Generated by Django 3.2.13 on 2023-08-02 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0002_inventarioingresobodega_movimiento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, choices=[('ingreso_importacion', 'Ingreso Importación'), ('movimiento_interno', 'Movimiento Interno'), ('egreso_picking', 'Egreso Picking'), ('ajuste_inventario', 'Ajuste Inventario')], max_length=20, verbose_name='Descripción del movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='n_referencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numero de referencia'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('picking', 'PICKING'), ('ajuste', 'AJUSTE')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
