# Generated by Django 3.2.13 on 2023-08-02 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0003_auto_20230802_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_hora',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Fecha Hora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, choices=[('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Egreso Picking', 'Egreso Picking'), ('Ajuste Inventario', 'Ajuste Inventario')], max_length=20, verbose_name='Descripción del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Picking', 'Picking'), ('Ajuste', 'Ajuste')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10, verbose_name='Tipo de movimiento'),
        ),
    ]
