# Generated by Django 3.2.13 on 2023-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0004_auto_20230802_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora'),
        ),
    ]
