# Generated by Django 3.2.13 on 2023-08-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0005_alter_movimiento_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='wms.inventarioingresobodega', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='wms.ubicacion', verbose_name='Ubicación'),
        ),
    ]
