# Generated by Django 3.2.13 on 2023-10-31 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20230802_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioingresobodega',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='inventarioingresobodega',
            name='marca2',
        ),
        migrations.RemoveField(
            model_name='inventarioingresobodega',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='inventarioingresobodega',
            name='o_compra',
        ),
        migrations.AddField(
            model_name='inventarioingresobodega',
            name='fecha_elaboracion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de elaboración'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventarioingresobodega',
            name='n_referencia',
            field=models.CharField(blank=True, max_length=50, verbose_name='N°. Referencia'),
        ),
        migrations.AddField(
            model_name='inventarioingresobodega',
            name='referencia',
            field=models.CharField(choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Ajuste', 'Ajuste')], default=django.utils.timezone.now, max_length=50, verbose_name='Referencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventarioingresobodega',
            name='bodega',
            field=models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7'), ('CUC', 'CUC')], max_length=5, verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='bodega',
            field=models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7'), ('CUC', 'CUC')], max_length=10, verbose_name='Bodega'),
        ),
    ]
