# Generated by Django 3.2.13 on 2023-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_auto_20231031_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='item',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='distancia_puerta',
            field=models.FloatField(blank=True, null=True, verbose_name='Capacidad m3'),
        ),
    ]
