# Generated by Django 3.2.13 on 2023-10-31 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0008_auto_20231031_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='item',
            field=models.ForeignKey(default='001', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='wms.inventarioingresobodega', verbose_name='Item'),
            preserve_default=False,
        ),
    ]
