# Generated by Django 3.2.13 on 2023-11-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0009_movimiento_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioingresobodega',
            name='fecha_elaboracion',
        ),
    ]
