# Generated by Django 3.2.13 on 2023-11-06 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0010_remove_inventarioingresobodega_fecha_elaboracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioingresobodega',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Hora'),
            preserve_default=False,
        ),
    ]
