# Generated by Django 3.2.13 on 2023-11-07 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0011_inventarioingresobodega_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='item',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_caducidad',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de caducidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='lote_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Lote id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='product_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Product id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Descripción del movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Picking', 'Picking'), ('Ajuste', 'Ajuste')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
    ]
