# Generated by Django 3.2.13 on 2023-11-08 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0012_auto_20231107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Picking', 'Picking'), ('Ajuste', 'Ajuste')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('lote_id', models.CharField(max_length=50, verbose_name='Lote id')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('unidades', models.IntegerField(verbose_name='Unidades ingresadas')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora')),
                ('ubicacion', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='existencias_ubicacion', to='wms.ubicacion', verbose_name='Ubicación')),
            ],
        ),
    ]
