# Generated by Django 3.2.13 on 2023-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0013_auto_20231108_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existencias',
            name='unidades',
            field=models.PositiveIntegerField(verbose_name='Unidades ingresadas'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Ajuste', 'Ajuste'), ('Picking', 'Picking')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
    ]
