# Generated by Django 3.2.13 on 2023-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0015_auto_20231122_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='despacho',
            field=models.BooleanField(default=True, verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='existencias',
            name='cuarentena',
            field=models.BooleanField(default=False, verbose_name='Cuarentena'),
        ),
    ]
