# Generated by Django 3.2.13 on 2023-12-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0016_auto_20231129_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioingresobodega',
            name='id_ref',
            field=models.IntegerField(blank=True, default=0, verbose_name='Id referencia'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='despacho',
            field=models.BooleanField(default=False, verbose_name='Despacho'),
        ),
    ]
