# Generated by Django 3.2.13 on 2023-12-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0017_auto_20231218_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencias',
            name='cuarentena',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='cuarentena',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='despacho',
        ),
        migrations.AddField(
            model_name='existencias',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cuarentena', 'Cuarentena'), ('Disponible', 'Disponible'), ('En Despacho', 'En Despacho'), ('Despachado', 'Despachado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('Cuarentena', 'Cuarentena'), ('Disponible', 'Disponible'), ('En Despacho', 'En Despacho'), ('Despachado', 'Despachado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='inventarioingresobodega',
            name='bodega',
            field=models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7')], max_length=5, verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='inventarioingresobodega',
            name='id_ref',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id referencia'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='bodega',
            field=models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7')], max_length=10, verbose_name='Bodega'),
        ),
    ]
