# Generated by Django 3.2.13 on 2023-12-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0019_auto_20231221_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='wms.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='distancia_puerta',
            field=models.FloatField(blank=True, null=True, verbose_name='Distancia a puerta'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='modulo',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09')], max_length=10, verbose_name='ModuloPalet'),
        ),
    ]
