# Generated by Django 3.2.13 on 2023-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0020_auto_20231222_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='modulo',
            field=models.CharField(max_length=10, verbose_name='ModuloPalet'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nivel',
            field=models.CharField(max_length=10, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='pasillo',
            field=models.CharField(max_length=10, verbose_name='Pasillo'),
        ),
    ]
