# Generated by Django 3.2.13 on 2023-12-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0021_auto_20231222_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencias',
            name='ubicacion',
        ),
    ]
