# Generated by Django 3.2.13 on 2023-12-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0022_remove_existencias_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='ubicacion',
        ),
    ]
