# Generated by Django 3.2.13 on 2023-12-22 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0023_remove_movimiento_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencias',
            name='ubicacion',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existencias_ubicacion', to='wms.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='wms.ubicacion', verbose_name='Ubicación'),
        ),
    ]
