# Generated by Django 3.2.13 on 2023-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0024_auto_20231222_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Hora'),
        ),
    ]
