# Generated by Django 3.2.13 on 2024-01-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0025_movimiento_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_gimp', models.CharField(max_length=50, verbose_name='Doc - GIMPR')),
                ('n_trasferencia', models.CharField(max_length=50, verbose_name='Número de trasferencia')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('lote_id', models.CharField(max_length=50, verbose_name='Lote id')),
                ('fecha_caducidad', models.DateField(verbose_name='Fecha de caducidad')),
                ('bodega_salida', models.CharField(max_length=10, verbose_name='Bodega de salida')),
                ('unidades', models.PositiveIntegerField(verbose_name='Unidades ingresadas')),
            ],
        ),
    ]
