# Generated by Django 3.2.13 on 2024-01-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0026_trasferencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasferencia',
            new_name='Transferencia',
        ),
    ]
