# Generated by Django 3.2.13 on 2024-01-10 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0027_rename_trasferencia_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Hora'),
            preserve_default=False,
        ),
    ]
