# Generated by Django 3.2.13 on 2024-01-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0028_transferencia_fecha_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='n_trasferencia',
            new_name='n_transferencia',
        ),
    ]
