# Generated by Django 3.2.13 on 2024-01-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0029_rename_n_trasferencia_transferencia_n_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='n_factura',
            field=models.CharField(blank=True, max_length=40, verbose_name='Factura despachado'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Liberación', 'Liberación'), ('Ajuste', 'Ajuste'), ('Picking', 'Picking'), ('Transferencia', 'Transferencia')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
    ]
