# Generated by Django 3.2.13 on 2024-02-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0031_liberacioncuarentena_notaentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnulacionPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking_anulado', models.CharField(max_length=50, verbose_name='Pikcing nulado')),
                ('picking_nuevo', models.CharField(max_length=50, verbose_name='Pikcing nuevo')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora')),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Liberación', 'Liberación'), ('Ajuste', 'Ajuste'), ('Picking', 'Picking'), ('Transferencia', 'Transferencia'), ('Nota de entrega', 'Nota de entrega')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
    ]
