# Generated by Django 3.2.13 on 2024-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0033_anulacionpicking_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anulacionpicking',
            name='picking_anulado',
            field=models.CharField(max_length=50, unique=True, verbose_name='Pikcing nulado'),
        ),
    ]
