# Generated by Django 3.2.13 on 2024-02-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0034_alter_anulacionpicking_picking_anulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_transferencia', models.CharField(max_length=50, verbose_name='Número de trasferencia')),
                ('unidades', models.PositiveIntegerField(verbose_name='Unidades ingresadas')),
                ('estado', models.CharField(max_length=20, verbose_name='Número de trasferencia')),
            ],
        ),
    ]
