# Generated by Django 3.2.13 on 2024-02-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0035_transferenciastatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciastatus',
            name='unidades',
        ),
        migrations.AddField(
            model_name='transferenciastatus',
            name='unidades_mba',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades mba'),
        ),
        migrations.AddField(
            model_name='transferenciastatus',
            name='unidades_wms',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades wms'),
        ),
        migrations.AlterField(
            model_name='transferenciastatus',
            name='estado',
            field=models.CharField(max_length=20, verbose_name='Estado'),
        ),
    ]
