# Generated by Django 3.2.13 on 2024-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0036_auto_20240215_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastatus',
            name='avance',
            field=models.FloatField(default=0.0, verbose_name='Avance'),
        ),
    ]
