# Generated by Django 3.2.13 on 2024-02-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0038_alter_transferenciastatus_n_transferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteLiberacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id_corp', models.CharField(max_length=255, verbose_name='Doc id corp')),
                ('doc_id', models.CharField(max_length=255, verbose_name='Doc id')),
                ('tipo', models.CharField(choices=[('Liberación Etiquetado', 'Liberación Etiquetado'), ('Liberación Importación', 'Liberación Importación')], max_length=50, verbose_name='Tipo')),
                ('product_id', models.CharField(max_length=255, verbose_name='Product id')),
                ('lote_id', models.CharField(max_length=255, verbose_name='Lote id')),
                ('ware_code', models.CharField(max_length=50, verbose_name='Bodega')),
                ('location', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('egreso_temp', models.PositiveIntegerField(verbose_name='Egreso temp')),
                ('commited', models.PositiveIntegerField(verbose_name='Commited')),
                ('fecha_caducidad', models.DateTimeField(verbose_name='Fecha caducidad')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='liberacioncuarentena',
            unique_together=set(),
        ),
    ]
