# Generated by Django 3.2.13 on 2024-03-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0039_auto_20240228_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteliberacion',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='ajusteliberacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_cuc_liberacion', to='wms.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='ajusteliberacion',
            name='unidades_cuc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades cuarentena'),
        ),
    ]
