# Generated by Django 3.2.13 on 2024-03-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0041_alter_ajusteliberacion_fecha_caducidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntregatatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_entrega', models.CharField(max_length=50, unique=True, verbose_name='Número de nota de entrega')),
                ('unidades_mba', models.PositiveIntegerField(default=0, verbose_name='Unidades mba')),
                ('unidades_wms', models.PositiveIntegerField(default=0, verbose_name='Unidades wms')),
                ('avance', models.FloatField(default=0.0, verbose_name='Avance')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.AlterField(
            model_name='ajusteliberacion',
            name='tipo',
            field=models.CharField(choices=[('Liberación Acondicionamiento', 'Liberación Acondicionamiento'), ('Liberación Importación', 'Liberación Importación')], max_length=50, verbose_name='Tipo'),
        ),
    ]
