# Generated by Django 3.2.13 on 2024-03-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0042_auto_20240313_0811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotaEntregatatus',
            new_name='NotaEntregaStatus',
        ),
    ]
