# Generated by Django 3.2.13 on 2024-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0043_rename_notaentregatatus_notaentregastatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='estado_picking',
            field=models.CharField(blank=True, choices=[('En Despacho', 'En Despacho'), ('Despachado', 'Despachado'), ('No Despachado', 'No Despachado')], max_length=20, verbose_name='Estado Picking'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Liberación', 'Liberación'), ('Ajuste', 'Ajuste'), ('Picking', 'Picking'), ('Reverso de picking', 'Reverso de picking'), ('Transferencia', 'Transferencia'), ('Nota de entrega', 'Nota de entrega')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
    ]
