# Generated by Django 3.2.13 on 2024-06-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0044_auto_20240319_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Hora Actualización'),
        ),
    ]
