# Generated by Django 3.2.13 on 2024-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0045_alter_movimiento_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ubicacion'),
        ),
    ]
