# Generated by Django 3.2.13 on 2024-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0047_ubicacion_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
