# Generated by Django 3.2.13 on 2024-09-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0050_alter_ubicacion_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespachoCarton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking', models.CharField(max_length=10)),
                ('factura', models.CharField(max_length=30)),
                ('cartones_calculados', models.FloatField()),
                ('cartones_fisicos', models.FloatField()),
            ],
        ),
    ]
