# Generated by Django 3.2.13 on 2024-09-02 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0051_despachocarton'),
    ]

    operations = [
        migrations.AddField(
            model_name='despachocarton',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Hora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despachocarton',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
