# Generated by Django 3.2.13 on 2024-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0052_auto_20240902_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachocarton',
            name='picking',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
