# Generated by Django 3.2.25 on 2024-10-01 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wms', '0053_alter_despachocarton_picking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoArmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('lote_id', models.CharField(max_length=50, verbose_name='Lote id')),
                ('fecha_elaboracion', models.DateField(blank=True, verbose_name='Fecha de elaboración')),
                ('fecha_caducidad', models.DateField(blank=True, verbose_name='Fecha de caducidad')),
                ('ubicacion', models.CharField(blank=True, max_length=12, verbose_name='Ubicacion')),
                ('unidades', models.IntegerField(blank=True, verbose_name='Unidades ingresadas')),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='referencia',
            field=models.CharField(blank=True, choices=[('Inventario Inicial', 'Inventario Inicial'), ('Ingreso Importación', 'Ingreso Importación'), ('Movimiento Interno', 'Movimiento Interno'), ('Movimiento Grupal', 'Movimiento Grupal'), ('Liberación', 'Liberación'), ('Ajuste', 'Ajuste'), ('Picking', 'Picking'), ('Reverso de picking', 'Reverso de picking'), ('Transferencia', 'Transferencia'), ('Nota de entrega', 'Nota de entrega')], max_length=20, verbose_name='Referencia del movimiento'),
        ),
        migrations.CreateModel(
            name='OrdenEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('cliente', models.CharField(blank=True, max_length=70, verbose_name='Cliente')),
                ('bodega', models.CharField(blank=True, max_length=20, verbose_name='Bodega')),
                ('prioridad', models.CharField(blank=True, choices=[('Inmediato', 'Inmediato'), ('Urgente (2 días)', 'Urgente (2 días)'), ('Pronto (1 semana)', 'Pronto (1 semana)')], max_length=20, verbose_name='Prioridad')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Hora')),
                ('componentes', models.ManyToManyField(related_name='componentes', to='wms.ProductoArmado')),
                ('nuevo_producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_producto', to='wms.productoarmado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
