# Generated by Django 3.2.25 on 2024-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0054_auto_20241001_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenempaque',
            name='estado',
            field=models.CharField(blank=True, choices=[('Creado', 'Creado'), ('En Picking', 'En Picking'), ('En Proceso', 'En Proceso'), ('En Pausa', 'En Pausa'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='ordenempaque',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
