# Generated by Django 3.2.25 on 2024-10-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0056_auto_20241001_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoarmado',
            name='precio_venta',
            field=models.FloatField(null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='bodega',
            field=models.CharField(blank=True, choices=[('Andagoya', 'Andagoya'), ('Cerezos', 'Cerezos')], max_length=20, verbose_name='Bodega'),
        ),
    ]
