# Generated by Django 3.2.25 on 2024-10-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0057_auto_20241002_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenempaque',
            name='bodega',
            field=models.CharField(choices=[('Andagoya', 'Andagoya'), ('Cerezos', 'Cerezos')], max_length=20, verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='cliente',
            field=models.CharField(max_length=70, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='estado',
            field=models.CharField(choices=[('Creado', 'Creado'), ('En Picking', 'En Picking'), ('En Proceso', 'En Proceso'), ('En Pausa', 'En Pausa'), ('Finalizado', 'Finalizado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='prioridad',
            field=models.CharField(choices=[('Inmediato', 'Inmediato'), ('Urgente (2 días)', 'Urgente (2 días)'), ('Pronto (1 semana)', 'Pronto (1 semana)')], max_length=20, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='ruc',
            field=models.CharField(max_length=13, verbose_name='RUC'),
        ),
    ]
