# Generated by Django 3.2.25 on 2024-10-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0058_auto_20241002_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenempaque',
            name='nuevo_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_producto', to='wms.productoarmado'),
        ),
    ]
