# Generated by Django 3.2.25 on 2024-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0059_alter_ordenempaque_nuevo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoarmado',
            name='marca',
            field=models.CharField(default='', max_length=50, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoarmado',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
