# Generated by Django 3.2.25 on 2024-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0060_auto_20241002_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoarmado',
            name='lote_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Lote id'),
        ),
        migrations.AlterField(
            model_name='productoarmado',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='productoarmado',
            name='unidades',
            field=models.IntegerField(blank=True, verbose_name='Cantidad'),
        ),
    ]
