# Generated by Django 3.2.25 on 2024-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0061_auto_20241002_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoarmado',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de caducidad'),
        ),
        migrations.AlterField(
            model_name='productoarmado',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de elaboración'),
        ),
    ]
