# Generated by Django 3.2.25 on 2024-11-19 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0063_auto_20241028_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoarmado',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
