# Generated by Django 3.2.25 on 2024-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0064_productoarmado_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenempaque',
            name='archivo',
            field=models.FileField(null=True, upload_to='orden_empaque'),
        ),
    ]
