# Generated by Django 5.1.4 on 2025-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0065_ordenempaque_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenempaque',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='ordenempaque',
            name='estado',
            field=models.CharField(choices=[('Creado', 'Creado'), ('En Picking', 'En Picking'), ('En Proceso', 'En Proceso'), ('En Pausa', 'En Pausa'), ('Finalizado', 'Finalizado'), ('Anulado', 'Anulado')], max_length=20, verbose_name='Estado'),
        ),
    ]
