# Generated by Django 5.1.4 on 2025-02-28 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0068_facturaanulada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaanulada',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
    ]
