# Generated by Django 5.1.4 on 2025-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0070_facturaanulada_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaanulada',
            name='n_factura',
            field=models.CharField(max_length=13, unique=True, verbose_name='Factura'),
        ),
    ]
