# Generated by Django 5.1.4 on 2025-05-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0073_transferencia_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='fecha_elaboracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de elaboracion'),
        ),
    ]
