# Generated by Django 5.1.4 on 2025-09-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0075_importacionfotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionfotos',
            name='marca',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='importacionfotos',
            name='proveedor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
