# Generated by Django 5.1.4 on 2025-09-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0076_importacionfotos_marca_importacionfotos_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('costo_unitario', models.FloatField()),
                ('dolar_importado', models.FloatField(blank=True)),
                ('importacion', models.CharField(max_length=30)),
                ('gim', models.CharField(max_length=30)),
                ('fecha_llegada', models.DateField()),
            ],
        ),
    ]
