# Generated by Django 5.1.4 on 2025-09-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0077_costoimportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costoimportacion',
            name='dolar_importado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
