# Generated by Django 5.1.4 on 2025-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0078_alter_costoimportacion_dolar_importado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costoimportacion',
            name='marca',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='costoimportacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
