# Generated by Django 5.1.4 on 2025-09-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0079_alter_costoimportacion_marca_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costoimportacion',
            unique_together={('product_id', 'importacion')},
        ),
    ]
