# Generated by Django 5.1.4 on 2025-10-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0080_alter_costoimportacion_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_factura', models.CharField(max_length=30, unique=True)),
                ('codigo_cliente', models.CharField(max_length=30)),
                ('ruc_cliente', models.CharField(max_length=13)),
                ('cliente', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
