# Generated by Django 5.1.4 on 2025-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0081_ordensalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordensalida',
            name='fecha_factura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
