# Generated by Django 5.1.4 on 2026-02-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0082_ordensalida_fecha_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastatus',
            name='creado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciastatus',
            name='en_proceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferenciastatus',
            name='finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
