# Generated by Django 5.1.4 on 2026-02-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0083_transferenciastatus_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciastatus',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
