# Generated by Django 5.1.4 on 2026-02-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0084_alter_transferenciastatus_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaanulada',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
