# Generated by Django 5.1.4 on 2026-02-12 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0085_facturaanulada_codigo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaanulada',
            name='fecha_reemplazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='nueva_factura',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='nuevo_picking',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='facturaanulada',
            name='usuario_reemplazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_reemplazo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='facturaanulada',
            name='estado',
            field=models.CharField(choices=[('Anulado', 'Anulado'), ('Pendiente', 'Pendiente'), ('Reemplazado', 'Reemplazado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='facturaanulada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_anulacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
