# Generated by Django 5.1.4 on 2026-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0086_facturaanulada_fecha_reemplazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descripción del movimiento'),
        ),
    ]
