# Generated by Django 5.1.4 on 2026-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0087_alter_movimiento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastatus',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='transf_excel/'),
        ),
    ]
