# Generated by Django 5.1.4 on 2026-02-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0088_transferenciastatus_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciastatus',
            name='n_transferencia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de trasferencia'),
        ),
    ]
