# Generated by Django 5.1.4 on 2026-02-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0060_pickingestadistica_ciudad_cliente_and_more'),
        ('wms', '0089_alter_transferenciastatus_n_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastatus',
            name='camion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.vehiculos'),
        ),
    ]
