# Generated by Django 5.1.4 on 2026-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0091_alter_transferenciastatus_n_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciastatus',
            name='ingresado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
