# Generated by Django 5.1.4 on 2026-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_notificacioncartera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacioncartera',
            old_name='correo',
            new_name='correo_text',
        ),
    ]
