# Generated by Django 5.1.4 on 2026-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_rename_correo_notificacioncartera_correo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacioncartera',
            name='codigo_cliente',
            field=models.CharField(max_length=20),
        ),
    ]
