# Generated by Django 3.2.13 on 2022-07-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('ubicacion', models.CharField(choices=[('Andagoya', 'Andagoya'), ('Cerezos', 'Cerezos')], max_length=50, verbose_name='Ubicación')),
                ('frecuencia', models.CharField(blank=True, max_length=200, verbose_name='Fecuencia de mantenimiento')),
                ('mtt_por', models.CharField(blank=True, max_length=200, verbose_name='Empresa que realiza el mantenimiento')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(blank=True, verbose_name='Cantidad')),
                ('precio', models.FloatField(blank=True, verbose_name='Precio')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='Observacion')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo', verbose_name='Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Mantenimiento Preventivo', 'Mantenimiento Preventivo'), ('Mantenimiento Correctivo', 'Mantenimiento Correctivo')], max_length=30, verbose_name='Tipo de mantenimiento')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='Observación')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo', verbose_name='Equipo')),
                ('producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.suministro', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_detectados', models.IntegerField(blank=True, verbose_name='Productos detectados')),
                ('c_mens', models.IntegerField(blank=True, verbose_name='Cuenta de mensajes')),
                ('f_seniales', models.IntegerField(blank=True, verbose_name='Fallos de señal')),
                ('h_maquina', models.DurationField(blank=True, verbose_name='Horas máquina')),
                ('h_chorro', models.DurationField(blank=True, verbose_name='Horas chorro')),
                ('observacion', models.CharField(blank=True, max_length=300, verbose_name='Observación')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo', verbose_name='Equipo')),
            ],
        ),
    ]
