# Generated by Django 3.2.13 on 2023-08-30 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0002_alter_estadistica_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoPreventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('REALIZADO', 'REALIZADO')], max_length=100, verbose_name='Estado')),
                ('programado', models.DateField(verbose_name='Programado para')),
                ('actividad', models.CharField(choices=[('Limpieza de cabezal', 'Limpieza de cabezal'), ('Limpieza de Filtro', 'Limpieza de Filtro')], max_length=100, verbose_name='Estado')),
                ('realizado', models.DateTimeField(blank=True, verbose_name='Realizado en')),
                ('observaciones', models.CharField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mtto_preventivo/', verbose_name='Foto')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.equipo', verbose_name='Equipo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
        ),
    ]
