# Generated by Django 3.2.13 on 2023-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_mantenimientopreventivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='actividad',
            field=models.CharField(choices=[('Limpieza de cabezal', 'Limpieza de cabezal'), ('Limpieza de Filtro', 'Limpieza de Filtro')], max_length=100, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='realizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Realizado en'),
        ),
    ]
