# Generated by Django 3.2.13 on 2023-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_auto_20230830_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='actividad',
            field=models.CharField(choices=[('Limpieza de Cabezal', 'Limpieza de Cabezal'), ('Limpieza de Filtro', 'Limpieza de Filtro')], max_length=100, verbose_name='Actividad'),
        ),
    ]
