# Generated by Django 5.1.4 on 2025-05-16 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('estado_inv', models.CharField(blank=True, default='ABIERTO', max_length=50)),
                ('estado_tm', models.CharField(blank=True, default='CREADO', max_length=50)),
                ('inicio_tf', models.DateTimeField(blank=True, null=True)),
                ('fin_tf', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_app_metro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_gim', models.CharField(db_index=True, max_length=30, unique=True)),
                ('codigo_hm', models.CharField(max_length=30)),
                ('nombre_gim', models.CharField(max_length=100)),
                ('nombre_hm', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=30)),
                ('unidad', models.CharField(max_length=10)),
                ('u_empaque', models.IntegerField(blank=True, default=0, null=True)),
                ('consignacion', models.IntegerField(blank=True, default=0, null=True)),
                ('ubicacion', models.CharField(max_length=30)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='TomaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estanteria', models.IntegerField(blank=True)),
                ('cantidad_bulto', models.IntegerField(blank=True)),
                ('cantidad_total', models.IntegerField(blank=True)),
                ('observaciones', models.CharField(blank=True, max_length=150)),
                ('llenado', models.BooleanField(default=False)),
                ('agregado', models.BooleanField(default=False)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.inventario')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
