# Generated by Django 5.1.4 on 2025-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomafisica',
            name='cantidad_total',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
