# Generated by Django 5.1.4 on 2025-05-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0002_alter_tomafisica_cantidad_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomafisica',
            old_name='user',
            new_name='usuario',
        ),
    ]
