# Generated by Django 5.1.4 on 2025-05-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0003_rename_user_tomafisica_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='estado_tm',
            new_name='estado_tf',
        ),
    ]
