# Generated by Django 5.1.4 on 2025-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_rename_estado_tm_inventario_estado_tf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
