# Generated by Django 5.1.4 on 2025-07-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0006_tomafisica_cantidad_suministro'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orden',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomafisica',
            name='orden',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomafisica',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
