# Generated by Django 5.1.4 on 2025-08-12 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0007_product_orden_tomafisica_orden_tomafisica_revisado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=10)),
                ('description', models.CharField(choices=[('Saldo inicial', 'Saldo inicial'), ('Ajuste por acuerdo', 'Ajuste por acuerdo'), ('Incremento', 'Incremento'), ('Decremento', 'Decremento')], max_length=20)),
                ('nota_entrega', models.CharField(max_length=20)),
                ('fecha_nota', models.DateField()),
                ('movimiento_mba', models.CharField(max_length=20)),
                ('fecha_mba', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('documento', models.FileField(null=True, upload_to='metro_kardex')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_records', to='metro.product')),
            ],
        ),
    ]
