# Generated by Django 5.1.4 on 2025-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0009_kardex_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='metro_kardex'),
        ),
    ]
