# Generated by Django 5.1.4 on 2025-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0010_alter_kardex_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='factor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='precio_unitario',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha_mba',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='fecha_nota',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='movimiento_mba',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kardex',
            name='nota_entrega',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
