# Generated by Django 5.1.4 on 2025-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0011_product_factor_product_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kardex',
            name='tipo',
        ),
    ]
