# Generated by Django 5.1.4 on 2025-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0012_remove_kardex_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
