# Generated by Django 5.1.4 on 2025-09-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0013_kardex_confirmado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio_unitario',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
