# Generated by Django 5.1.4 on 2025-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0014_alter_product_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='description',
            field=models.CharField(choices=[('Saldo inicial', 'Saldo inicial'), ('Ajuste', 'Ajuste'), ('Incremento', 'Incremento'), ('Disminución', 'Disminución')], max_length=20),
        ),
    ]
