# Generated by Django 5.1.4 on 2026-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0016_cotizacion_cotizacionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivo_procesado',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
    ]
