# Generated by Django 5.1.4 on 2026-02-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0017_cotizacion_archivo_procesado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CotizacionItem',
        ),
    ]
