# Generated by Django 5.1.4 on 2026-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0018_delete_cotizacionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
