# Generated by Django 3.2.13 on 2022-07-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ofocio', models.IntegerField(null=True, verbose_name='N° Oficio')),
                ('oficio', models.CharField(max_length=30, verbose_name='Oficio')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente')),
                ('valido_hasta_mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=20, verbose_name='Valido hasta mes')),
                ('valido_hasta_anio', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=20, verbose_name='Valido hasta anio')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_carta_general', verbose_name='QR')),
            ],
        ),
        migrations.CreateModel(
            name='CartaProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ofocio', models.IntegerField(null=True, verbose_name='N° Oficio')),
                ('oficio', models.CharField(max_length=30, verbose_name='Oficio')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente')),
                ('hospital', models.CharField(max_length=100, verbose_name='Hospital')),
                ('proceso', models.CharField(max_length=50, verbose_name='N° Proceso')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_carta_procesos', verbose_name='QR')),
                ('marcas', models.ManyToManyField(to='datos.Marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='CartaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ofocio', models.IntegerField(null=True, verbose_name='N° Oficio')),
                ('oficio', models.CharField(max_length=30, verbose_name='Oficio')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('cliente', models.CharField(max_length=50, verbose_name='Cliente')),
                ('hospital', models.CharField(max_length=100, verbose_name='Hospital')),
                ('proceso', models.CharField(max_length=50, verbose_name='N° Proceso')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('slug', models.SlugField(unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_carta_procesos', verbose_name='QR')),
                ('items', models.ManyToManyField(to='datos.Product', verbose_name='Productos')),
            ],
        ),
        migrations.CreateModel(
            name='AnularCartaProcesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de anulación')),
                ('slug', models.SlugField(unique=True)),
                ('cartaprocesos', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carta.cartaprocesos', verbose_name='Carta Procesos')),
            ],
        ),
        migrations.CreateModel(
            name='AnularCartaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de anulación')),
                ('slug', models.SlugField(unique=True)),
                ('cartaitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carta.cartaitem', verbose_name='Carta Procesos')),
            ],
        ),
        migrations.CreateModel(
            name='AnularCartaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de anulación')),
                ('slug', models.SlugField(unique=True)),
                ('cartageneral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='carta.cartageneral', verbose_name='Carta General')),
            ],
        ),
    ]
