# Generated by Django 3.2.13 on 2022-11-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0002_auto_20221118_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaprocesos',
            name='cliente',
            field=models.CharField(max_length=150, verbose_name='Cliente'),
        ),
    ]
