# Generated by Django 3.2.13 on 2023-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_alter_cartaprocesos_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartageneral',
            name='cliente',
            field=models.CharField(max_length=250, verbose_name='Cliente'),
        ),
    ]
