# Generated by Django 3.2.13 on 2023-03-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230322_0848'),
        ('carta', '0005_auto_20230322_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anularcartageneral',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='anularcartaitem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='anularcartaprocesos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cartageneral',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cartaitem',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='cartaprocesos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userperfil', verbose_name='Usuario'),
        ),
    ]
