# Generated by Django 3.2.13 on 2023-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0006_auto_20230322_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaprocesos',
            name='autorizacion',
            field=models.CharField(blank=True, max_length=450, verbose_name='Autorización'),
        ),
    ]
