# Generated by Django 5.1.4 on 2025-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0010_cartaitem_items_mba_alter_cartaitem_items'),
        ('datos', '0033_adminactualizationwarehaouse_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaitem',
            name='items',
            field=models.ManyToManyField(blank=True, to='datos.product', verbose_name='Productos'),
        ),
    ]
