# Generated by Django 5.1.4 on 2025-08-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0011_alter_cartaitem_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartageneral',
            name='valido_hasta_anio',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=20, verbose_name='Valido hasta anio'),
        ),
    ]
