# Generated by Django 5.1.4 on 2025-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0012_alter_cartageneral_valido_hasta_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaitem',
            name='proceso',
            field=models.CharField(max_length=250, verbose_name='N° Proceso'),
        ),
    ]
