# Generated by Django 5.1.4 on 2025-10-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0013_alter_cartaitem_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaitem',
            name='proceso',
            field=models.CharField(max_length=400, verbose_name='N° Proceso'),
        ),
    ]
