# Generated by Django 3.2.13 on 2023-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('lote_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('f_caducidad', models.DateField(blank=True, null=True, verbose_name='F.Caducidad')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_lotes', verbose_name='Documento')),
            ],
        ),
    ]
