# Generated by Django 3.2.13 on 2023-04-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0002_documentolote_o_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentolote',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
