# Generated by Django 3.2.13 on 2023-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0003_documentolote_actualizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentolote',
            name='actualizado',
        ),
    ]
