# Generated by Django 3.2.13 on 2023-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0004_remove_documentolote_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentolote',
            name='lote_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='documentolote',
            name='o_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de compra'),
        ),
    ]
