# Generated by Django 3.2.13 on 2023-06-20 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatorio_legal', '0005_auto_20230609_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_factura', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura')),
                ('codigo_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código cliente')),
                ('nombre_cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre cliente')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo cliente')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('fecha_hora', models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Orden de compra')),
                ('usuario', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
