# Generated by Django 3.2.13 on 2023-06-20 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0006_documentoenviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoenviado',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Orden de compra'),
            preserve_default=False,
        ),
    ]
