# Generated by Django 3.2.25 on 2024-09-20 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatorio_legal', '0007_alter_documentoenviado_fecha_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateField()),
                ('documento', models.FileField(upload_to='registros_sanitarios')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosLegales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=50)),
                ('nombre_marca_completo', models.CharField(max_length=50)),
                ('documento', models.FileField(upload_to='isos')),
                ('fecha_expiracion_iso', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('registros_sanitarios', models.ManyToManyField(to='regulatorio_legal.RegistroSanitario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
