# Generated by Django 3.2.25 on 2024-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0008_documentoslegales_registrosanitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoslegales',
            name='marca_de_agua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrosanitario',
            name='marca_de_agua',
            field=models.BooleanField(default=False),
        ),
    ]
