# Generated by Django 3.2.25 on 2024-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0009_auto_20240920_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosRegistoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='documentoslegales',
            old_name='fecha_expiracion_iso',
            new_name='fecha_caducidad',
        ),
        migrations.RenameField(
            model_name='documentoslegales',
            old_name='nombre_marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='documentoslegales',
            old_name='nombre_marca_completo',
            new_name='nombre_proveedor',
        ),
        migrations.RenameField(
            model_name='registrosanitario',
            old_name='product_id',
            new_name='n_reg_sanitario',
        ),
        migrations.RemoveField(
            model_name='documentoslegales',
            name='marca_de_agua',
        ),
        migrations.RemoveField(
            model_name='registrosanitario',
            name='marca_de_agua',
        ),
        migrations.AddField(
            model_name='registrosanitario',
            name='descripcion',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosanitario',
            name='nombre',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosanitario',
            name='productos',
            field=models.ManyToManyField(to='regulatorio_legal.ProductosRegistoSanitario'),
        ),
    ]
