# Generated by Django 3.2.25 on 2024-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0010_auto_20240920_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoslegales',
            name='registros_sanitarios',
            field=models.ManyToManyField(blank=True, null=True, to='regulatorio_legal.RegistroSanitario'),
        ),
    ]
