# Generated by Django 3.2.25 on 2024-09-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0011_alter_documentoslegales_registros_sanitarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoslegales',
            name='registros_sanitarios',
            field=models.ManyToManyField(blank=True, to='regulatorio_legal.RegistroSanitario'),
        ),
    ]
