# Generated by Django 3.2.25 on 2024-09-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0012_alter_documentoslegales_registros_sanitarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosRegistoSanitario',
            new_name='ProductosRegistroSanitario',
        ),
    ]
