# Generated by Django 3.2.25 on 2024-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0013_rename_productosregistosanitario_productosregistrosanitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosanitario',
            name='productos',
            field=models.ManyToManyField(blank=True, to='regulatorio_legal.ProductosRegistroSanitario'),
        ),
    ]
