# Generated by Django 3.2.25 on 2024-09-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0014_alter_registrosanitario_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosanitario',
            name='nombre',
        ),
    ]
