# Generated by Django 3.2.25 on 2024-10-28 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regulatorio_legal', '0015_remove_registrosanitario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsosRegEnviados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=60)),
                ('documento', models.FileField(blank=True, null=True, upload_to='doc_legales_enviados')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(max_length=10)),
                ('n_comprobante', models.CharField(max_length=30)),
                ('productos', models.TextField()),
                ('codigo_cliente', models.CharField(max_length=10)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('marca_de_agua', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('documentos', models.ManyToManyField(to='regulatorio_legal.IsosRegEnviados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
