# Generated by Django 3.2.25 on 2024-10-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0016_facturaproforma_isosregenviados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaproforma',
            old_name='productos',
            new_name='detalle',
        ),
    ]
