# Generated by Django 3.2.25 on 2024-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0017_rename_productos_facturaproforma_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isosregenviados',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='isosregenviados',
            name='tipo_documento',
            field=models.CharField(max_length=20),
        ),
    ]
