# Generated by Django 3.2.25 on 2024-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0018_auto_20241029_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproforma',
            name='email',
            field=models.BooleanField(default=False),
        ),
    ]
