# Generated by Django 3.2.25 on 2024-10-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0019_facturaproforma_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproforma',
            name='procesar_docs',
            field=models.BooleanField(default=False),
        ),
    ]
