# Generated by Django 5.1.4 on 2025-04-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0021_isosregenviados_url_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproforma',
            name='opacidad',
            field=models.CharField(default='3', max_length=2),
        ),
    ]
