# Generated by Django 5.1.4 on 2025-10-27 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0023_documentovario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='url_descarga',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='documentovario',
            name='email_envio',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de envío'),
        ),
        migrations.AddField(
            model_name='documentovario',
            name='marca_agua',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentovario',
            name='opacidad',
            field=models.CharField(default='3', max_length=2),
        ),
    ]
