# Generated by Django 5.1.4 on 2025-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0024_documento_creado_documento_procesado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentovario',
            name='opacidad',
            field=models.CharField(blank=True, default='3', max_length=2),
        ),
    ]
