# Generated by Django 5.1.4 on 2025-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0025_alter_documentovario_opacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentovario',
            name='docs_enviados',
            field=models.BooleanField(default=False),
        ),
    ]
