# Generated by Django 5.1.4 on 2025-10-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0026_documentovario_docs_enviados'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
