# Generated by Django 5.1.4 on 2025-10-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatorio_legal', '0027_documento_descripcion_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_otro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
