# Generated by Django 3.2.13 on 2022-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='MarcaImportExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='marcas_excel_import', verbose_name='Archivo Marcas Excel')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='Product id')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('marca2', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('unidad_empaque', models.IntegerField(verbose_name='Unidad Empaque')),
                ('largo', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caja master largo (m)')),
                ('ancho', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caja master ancho (m)')),
                ('alto', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caja master alto (m)')),
                ('volumen', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caja master volumen (m3)')),
                ('peso', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caja master peso (Kg)')),
                ('t_etiq_1p', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tiempo etiq 1 per (s)')),
                ('t_etiq_2p', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tiempo etiq 2 per (s)')),
                ('t_etiq_3p', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tiempo etiq 3 per (s)')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, verbose_name='Placa')),
                ('ancho', models.FloatField(verbose_name='Ancho (m)')),
                ('alto', models.FloatField(verbose_name='Alto (m)')),
                ('largo', models.FloatField(verbose_name='Largo (m)')),
                ('volumen', models.FloatField(verbose_name='Volumen (m3)')),
                ('volumen2', models.FloatField(verbose_name='Volumen -20% (m3)')),
            ],
        ),
    ]
