# Generated by Django 3.2.13 on 2022-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actulization_stoklote', models.CharField(max_length=50, verbose_name='Actulización Stock Lote')),
            ],
        ),
    ]
