# Generated by Django 3.2.13 on 2022-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='actulization_importaciones',
            field=models.CharField(blank=True, max_length=50, verbose_name='Actulización Importaciones'),
        ),
    ]
