# Generated by Django 3.2.13 on 2022-11-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_timestamp_actulization_importaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='empaque_primario',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Empaque primario'),
        ),
        migrations.AddField(
            model_name='product',
            name='empaque_secundario',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Empaque secundario'),
        ),
        migrations.AddField(
            model_name='product',
            name='empaquue_terciario',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Empaque terciario'),
        ),
    ]
