# Generated by Django 3.2.13 on 2022-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_rename_empaquue_terciario_product_empaque_terciario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='empaque_primario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque primario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='empaque_secundario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque secundario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='empaque_terciario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque terciario'),
        ),
    ]
