# Generated by Django 3.2.13 on 2022-11-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0006_auto_20221129_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='empaque_primario',
        ),
        migrations.RemoveField(
            model_name='product',
            name='empaque_secundario',
        ),
        migrations.RemoveField(
            model_name='product',
            name='empaque_terciario',
        ),
    ]
