# Generated by Django 3.2.13 on 2022-11-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_auto_20221129_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emp_primario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque primario'),
        ),
        migrations.AddField(
            model_name='product',
            name='emp_secundario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque secundario'),
        ),
        migrations.AddField(
            model_name='product',
            name='emp_terciario',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Empaque terciario'),
        ),
    ]
