# Generated by Django 3.2.13 on 2022-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_auto_20221129_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
