# Generated by Django 3.2.13 on 2022-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0009_vehiculos_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='transportista',
            field=models.CharField(blank=True, max_length=50, verbose_name='Trasportista'),
        ),
    ]
