# Generated by Django 3.2.13 on 2023-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0010_vehiculos_transportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unidad_empaque_box',
            field=models.IntegerField(null=True, verbose_name='Unidad Empaque Box'),
        ),
    ]
