# Generated by Django 3.2.13 on 2023-01-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0012_stockconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='actulization_stockconsulta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Actulización Stock Consulta'),
        ),
    ]
