# Generated by Django 3.2.13 on 2023-01-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0016_alter_timestamp_actulization_stockconsulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='actulization_stockconsulta',
        ),
    ]
