# Generated by Django 3.2.13 on 2023-01-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0017_remove_timestamp_actulization_stockconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='actulization_stockconsulta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Actulización Importaciones'),
        ),
    ]
