# Generated by Django 3.2.13 on 2023-01-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0018_timestamp_actulization_stockconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Producto activo'),
        ),
    ]
