# Generated by Django 3.2.13 on 2023-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0019_product_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Producto activo'),
        ),
    ]
