# Generated by Django 3.2.13 on 2023-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0020_alter_product_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='actulization_facturas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Actulización Facturas'),
        ),
    ]
