# Generated by Django 3.2.13 on 2023-06-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0022_timestamp_actualization_reserva_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='actualization_imp_llegadas',
            field=models.CharField(blank=True, max_length=50, verbose_name='Importaciones llegadas'),
        ),
    ]
