# Generated by Django 3.2.13 on 2023-07-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0024_product_t_armado'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='n_personas',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10, verbose_name='Número de personas para etiquetar'),
        ),
    ]
