# Generated by Django 3.2.13 on 2024-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0025_product_n_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('error', models.CharField(blank=True, max_length=250, null=True)),
                ('enviado', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
