# Generated by Django 3.2.13 on 2024-07-24 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0027_emailapilog_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailapilog',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
