# Generated by Django 3.2.13 on 2024-07-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0028_emailapilog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailapilog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
