# Generated by Django 3.2.25 on 2024-11-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0029_alter_emailapilog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActualizationWarehaouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50, unique=True)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
