# Generated by Django 3.2.25 on 2024-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0030_adminactualizationwarehaouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarcaImportExcel',
        ),
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='milisegundos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='periodicidad',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
