# Generated by Django 3.2.25 on 2024-11-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0031_auto_20241115_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
