# Generated by Django 3.2.25 on 2024-11-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0032_adminactualizationwarehaouse_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
    ]
