# Generated by Django 5.1.4 on 2025-02-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0033_adminactualizationwarehaouse_mensaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_id',)},
        ),
    ]
