# Generated by Django 5.1.4 on 2025-02-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0034_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidad_empaque',
            field=models.IntegerField(blank=True, verbose_name='Unidad Empaque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidad_empaque_box',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unidad Empaque Box'),
        ),
    ]
