# Generated by Django 5.1.4 on 2025-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0035_alter_product_description_alter_product_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unidad_empaque',
            field=models.IntegerField(blank=True, default=0, verbose_name='Unidad Empaque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidad_empaque_box',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidad Empaque Box'),
        ),
    ]
