# Generated by Django 5.1.4 on 2025-05-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0036_alter_product_unidad_empaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.CharField(blank=True, max_length=20)),
                ('codigo_cliente', models.CharField(blank=True, max_length=20)),
                ('product_id', models.CharField(blank=True, max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('ware_code', models.CharField(blank=True, max_length=5)),
                ('confirmed', models.IntegerField(default=0)),
                ('fecha_pedido', models.DateField(null=True)),
                ('hora_llegada', models.TimeField(null=True)),
                ('sec_name_cliente', models.CharField(blank=True, max_length=30)),
                ('unique_id', models.BigIntegerField(blank=True, null=True)),
                ('alterado', models.BooleanField(default=False)),
                ('creado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
