# Generated by Django 5.1.4 on 2025-07-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0038_reservas_actualizado_reservas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLoteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('lote_id', models.CharField(max_length=50)),
                ('oh', models.IntegerField(default=0)),
                ('oh2', models.IntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('error', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLoteReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('unds_total', models.IntegerField(default=0)),
                ('unds_lotes', models.IntegerField(default=0)),
                ('unds_diff', models.IntegerField(default=0)),
            ],
        ),
    ]
