# Generated by Django 5.1.4 on 2025-07-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0039_errorlotedetalle_errorlotereporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlotedetalle',
            name='commited_negativo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='errorlotedetalle',
            name='oh_transf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorlotereporte',
            name='commited_negativo',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='errorlotereporte',
            name='unds_total_mas_transf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='errorlotereporte',
            name='unds_transf',
            field=models.IntegerField(default=0),
        ),
    ]
