# Generated by Django 5.1.4 on 2025-08-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0041_errorlotev2'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlotev2',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
