# Generated by Django 5.1.4 on 2025-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0042_errorlotev2_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlotev2',
            name='diff_available',
            field=models.IntegerField(default=0),
        ),
    ]
