# Generated by Django 5.1.4 on 2025-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0043_errorlotev2_diff_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='sec_name_cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
