# Generated by Django 5.1.4 on 2025-11-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0044_alter_reservas_sec_name_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='sec_name_cliente',
            field=models.TextField(blank=True),
        ),
    ]
