# Generated by Django 5.1.4 on 2026-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0045_alter_reservas_sec_name_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlotev2',
            name='marca',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='errorlotev2',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
