# Generated by Django 5.1.4 on 2026-01-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0046_alter_errorlotev2_marca_alter_errorlotev2_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlotev2',
            name='marca',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='errorlotev2',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
