# Generated by Django 5.1.4 on 2026-01-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0047_alter_errorlotev2_marca_alter_errorlotev2_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlotev2',
            name='bodega',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
