# Generated by Django 5.1.4 on 2026-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0048_errorlotev2_bodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingEstadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.CharField(max_length=7, unique=True)),
                ('creado_mba', models.DateTimeField(blank=True, null=True)),
                ('anio_creado', models.IntegerField(default=0)),
                ('mes_creado', models.IntegerField(default=0)),
                ('dia_creado', models.IntegerField(default=0)),
                ('dia_semana_creado', models.CharField(blank=True, max_length=15)),
                ('bodega', models.CharField(blank=True, max_length=5)),
                ('creado_por_mba', models.CharField(blank=True, max_length=50)),
                ('codigo_cliente', models.CharField(blank=True, max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255)),
                ('tipo_cliente', models.CharField(blank=True, max_length=50)),
                ('inicio_picking', models.DateTimeField(blank=True, null=True)),
                ('fin_picking', models.DateTimeField(blank=True, null=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('total_volumen_m3', models.FloatField(default=0.0)),
                ('total_peso_kg', models.FloatField(default=0.0)),
                ('usuario_picking', models.CharField(blank=True, max_length=50)),
                ('tiempo_creacion_a_inicio', models.TimeField(blank=True, null=True)),
                ('tiempo_inicio_a_fin', models.TimeField(blank=True, null=True)),
                ('tiempo_fin_a_facturacion', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
