# Generated by Django 5.1.4 on 2026-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0049_pickingestadistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingestadistica',
            name='tiempo_total_proceso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
