# Generated by Django 5.1.4 on 2026-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0050_pickingestadistica_tiempo_total_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingestadistica',
            name='anio_creado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='dia_creado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='dia_semana_creado',
            field=models.PositiveSmallIntegerField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='mes_creado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_creacion_a_inicio',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_fin_a_facturacion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_inicio_a_fin',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_total_proceso',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='pickingestadistica',
            index=models.Index(fields=['anio_creado', 'mes_creado'], name='datos_picki_anio_cr_4d6f83_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingestadistica',
            index=models.Index(fields=['bodega'], name='datos_picki_bodega_1988fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingestadistica',
            index=models.Index(fields=['tipo_cliente'], name='datos_picki_tipo_cl_001191_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingestadistica',
            index=models.Index(fields=['usuario_picking'], name='datos_picki_usuario_316929_idx'),
        ),
    ]
