# Generated by Django 5.1.4 on 2026-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0051_alter_pickingestadistica_anio_creado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingestadistica',
            name='dia_semana_creado',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
