# Generated by Django 5.1.4 on 2026-01-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0052_alter_pickingestadistica_dia_semana_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingestadistica',
            name='dia_semana_creado_str',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
