# Generated by Django 5.1.4 on 2026-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0053_pickingestadistica_dia_semana_creado_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickingestadistica',
            name='bodega',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
