# Generated by Django 5.1.4 on 2026-01-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0055_pickingestadistica_datos_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingestadistica',
            name='creado_por_mba_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
