# Generated by Django 5.1.4 on 2026-01-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0056_pickingestadistica_creado_por_mba_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingestadistica',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
