# Generated by Django 5.1.4 on 2026-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0057_pickingestadistica_numero_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactualizationwarehaouse',
            name='actualizado_por',
            field=models.CharField(blank=True, default='api', max_length=15),
        ),
    ]
