# Generated by Django 5.1.4 on 2026-01-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0058_adminactualizationwarehaouse_actualizado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminactualizationwarehaouse',
            old_name='actualizado_por',
            new_name='conexion',
        ),
    ]
