# Generated by Django 5.1.4 on 2026-01-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0059_rename_actualizado_por_adminactualizationwarehaouse_conexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickingestadistica',
            name='ciudad_cliente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pickingestadistica',
            name='estado',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_creacion_a_inicio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_fin_a_facturacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_inicio_a_fin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickingestadistica',
            name='tiempo_total_proceso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
