# Generated by Django 5.1.4 on 2026-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0060_pickingestadistica_ciudad_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSlack',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
