# Generated by Django 5.1.4 on 2026-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0061_usuarioslack'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioslack',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioslack',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
