# Generated by Django 5.1.4 on 2026-03-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0062_usuarioslack_is_active_usuarioslack_last_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionSlack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo_msg', models.CharField(choices=[('Info', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('intervalo_minutos', models.PositiveIntegerField(default=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(related_name='notificaciones', to='datos.usuarioslack')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionInstanceSlack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(max_length=50)),
                ('referencia_id', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('envios', models.PositiveIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='datos.notificacionslack')),
            ],
        ),
    ]
