# Generated by Django 5.1.4 on 2026-03-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0063_notificacionslack_notificacioninstanceslack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionslack',
            name='intervalo_minutos',
        ),
        migrations.AlterField(
            model_name='notificacioninstanceslack',
            name='envios',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
