# Generated by Django 5.1.4 on 2026-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0064_remove_notificacionslack_intervalo_minutos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacioninstanceslack',
            name='proceso',
        ),
        migrations.AddField(
            model_name='notificacionslack',
            name='proceso',
            field=models.CharField(default='Transf', max_length=50),
            preserve_default=False,
        ),
    ]
