# Generated by Django 5.1.4 on 2026-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0065_remove_notificacioninstanceslack_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacioninstanceslack',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificacionslack',
            name='tipo_msg',
            field=models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20),
        ),
    ]
