# Generated by Django 5.1.4 on 2026-03-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0066_notificacioninstanceslack_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='unique_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
