# Generated by Django 5.1.4 on 2026-03-11 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0068_alter_reservas_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='unique_id',
            field=models.BigIntegerField(db_index=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
