# Generated by Django 5.1.4 on 2026-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0069_alter_reservas_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='unique_id',
            field=models.BigIntegerField(blank=True, db_index=True, unique=True),
        ),
    ]
