# Generated by Django 5.1.4 on 2026-03-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0071_alter_reservas_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='unique_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
