# Generated by Django 5.1.4 on 2026-03-11 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0072_alter_reservas_actualizado_alter_reservas_creado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='unique_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['unique_id'], name='datos_reser_unique__fee0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['activo'], name='datos_reser_activo_27890c_idx'),
        ),
        migrations.AddIndex(
            model_name='reservas',
            index=models.Index(fields=['creado'], name='datos_reser_creado_0a0f10_idx'),
        ),
    ]
