# Generated by Django 3.2.13 on 2022-08-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetadoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30, verbose_name='Código')),
                ('product_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('product_group', models.CharField(max_length=50, verbose_name='Marca')),
                ('o_etiq', models.FloatField(verbose_name='O.Etiquetado')),
                ('reservas', models.IntegerField(verbose_name='Reserva')),
                ('transito', models.IntegerField(verbose_name='Trnasito')),
                ('disp_reserva', models.IntegerField(verbose_name='Desp-Reserva')),
                ('mensual', models.IntegerField(verbose_name='Mensual')),
                ('cuarentena', models.IntegerField(verbose_name='Cuarentena')),
                ('tres_semanas', models.IntegerField(verbose_name='3Semanas')),
                ('stock_mensual', models.IntegerField(verbose_name='StockMensual')),
                ('meses', models.FloatField(verbose_name='Meses')),
            ],
        ),
    ]
