# Generated by Django 3.2.13 on 2022-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetadostock',
            name='disp_total',
            field=models.IntegerField(default=0, verbose_name='Desp-Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etiquetadostock',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
    ]
