# Generated by Django 3.2.13 on 2022-08-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
        ('etiquetado', '0003_etiquetadostock_actulizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datos.product', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('prod', models.ManyToManyField(blank=True, to='etiquetado.RowItem', verbose_name='Productos')),
            ],
        ),
    ]
