# Generated by Django 3.2.13 on 2022-08-26 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('etiquetado', '0004_calculadora_rowitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEtiquetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosEstadoEtiquetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pedido', models.CharField(max_length=50, unique=True, verbose_name='Pedido')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo', verbose_name='Equipo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetado.estadoetiquetado', verbose_name='Estado')),
            ],
        ),
    ]
