# Generated by Django 3.2.13 on 2022-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
        ('etiquetado', '0005_estadoetiquetado_pedidosestadoetiquetado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosestadoetiquetado',
            name='equipo',
        ),
        migrations.AddField(
            model_name='pedidosestadoetiquetado',
            name='equipo',
            field=models.ManyToManyField(blank=True, to='mantenimiento.Equipo', verbose_name='Equipo'),
        ),
    ]
