# Generated by Django 3.2.13 on 2022-09-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('etiquetado', '0006_auto_20220831_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowitem',
            name='lote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lote'),
        ),
        migrations.CreateModel(
            name='OrdenEtiquetadoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='Gimpromed Cía. Ltda.', max_length=100, verbose_name='Cliente')),
                ('tipo', models.CharField(default='STOCK', max_length=100, verbose_name='Tipo')),
                ('ciudad', models.CharField(default='Cerezos', max_length=100, verbose_name='Ciudad')),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('prod', models.ManyToManyField(blank=True, to='etiquetado.RowItem', verbose_name='Productos')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pedido', models.CharField(max_length=50, unique=True, verbose_name='Pedido')),
                ('estado', models.CharField(choices=[('EN PAUSA', 'EN PAUSA'), ('EN PROCESO', 'EN PROCESO'), ('INCOMPLETO', 'INCOMPLETO'), ('FINALIZADO', 'FINALIZADO')], max_length=50, verbose_name='Estado')),
                ('fecha_pedido', models.CharField(blank=True, max_length=50, verbose_name='Fecha pedido')),
                ('tipo_cliente', models.CharField(blank=True, max_length=50, verbose_name='Tipo cliente')),
                ('cliente', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
                ('detalle', models.TextField(verbose_name='Detalle')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userperfil', verbose_name='User')),
            ],
        ),
    ]
