# Generated by Django 3.2.13 on 2022-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0007_auto_20220927_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='bodega',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bodega'),
        ),
    ]
