# Generated by Django 3.2.13 on 2023-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0010_auto_20230124_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbodega',
            name='commited',
            field=models.FloatField(blank=True, verbose_name='Commited'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='oh',
            field=models.FloatField(blank=True, verbose_name='OH'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='oh2',
            field=models.FloatField(blank=True, verbose_name='OH2'),
        ),
        migrations.AlterField(
            model_name='stockbodega',
            name='quantity',
            field=models.FloatField(blank=True, verbose_name='Quantity'),
        ),
    ]
