# Generated by Django 3.2.13 on 2023-01-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0013_auto_20230124_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
