# Generated by Django 3.2.13 on 2023-02-13 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etiquetado', '0014_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetadostock',
            name='facturado',
            field=models.BooleanField(default=False, verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='etiquetadostock',
            name='facturado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='etiquetadostock',
            name='hora_facturado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Hoa de facturación'),
            preserve_default=False,
        ),
    ]
