# Generated by Django 3.2.13 on 2023-02-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etiquetado', '0015_auto_20230213_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetadostock',
            name='facturado',
        ),
        migrations.RemoveField(
            model_name='etiquetadostock',
            name='facturado_por',
        ),
        migrations.RemoveField(
            model_name='etiquetadostock',
            name='hora_facturado',
        ),
        migrations.AddField(
            model_name='estadopicking',
            name='facturado',
            field=models.BooleanField(default=False, verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='estadopicking',
            name='facturado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='estadopicking',
            name='hora_facturado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hoa de facturación'),
        ),
    ]
