# Generated by Django 3.2.13 on 2023-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0016_auto_20230213_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código Cliente'),
        ),
    ]
