# Generated by Django 3.2.13 on 2023-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0017_estadopicking_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopicking',
            name='fecha_actualizado',
            field=models.DateTimeField(verbose_name='Hora actualizado'),
        ),
        migrations.AlterField(
            model_name='estadopicking',
            name='hora_facturado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de facturación'),
        ),
    ]
