# Generated by Django 3.2.13 on 2023-03-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0018_auto_20230327_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopicking',
            name='fecha_actualizado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora actualizado'),
        ),
    ]
