# Generated by Django 3.2.13 on 2023-04-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0019_alter_estadopicking_fecha_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopicking',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
    ]
