# Generated by Django 3.2.13 on 2023-04-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230322_0848'),
        ('etiquetado', '0020_alter_estadopicking_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistoGuia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, max_length=150, verbose_name='Cliente')),
                ('factura', models.CharField(blank=True, max_length=50, verbose_name='Factura')),
                ('factura_c', models.CharField(blank=True, max_length=50, verbose_name='Factura completo')),
                ('ciudad', models.CharField(blank=True, max_length=50, verbose_name='Ciudad')),
                ('fecha_factura', models.DateField(blank=True, verbose_name='Fecha factura')),
                ('transpote', models.CharField(blank=True, max_length=30, verbose_name='Transporte')),
                ('fecha_conf', models.DateField(blank=True, verbose_name='Fecha confirmación')),
                ('n_guia', models.CharField(blank=True, max_length=150, verbose_name='Número de guía')),
                ('confirmado', models.TextField(verbose_name='Detalle')),
                ('bodega', models.CharField(blank=True, max_length=50, verbose_name='Bodega')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userperfil', verbose_name='User')),
            ],
        ),
    ]
