# Generated by Django 3.2.13 on 2023-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0022_auto_20230418_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='registoguia',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
