# Generated by Django 3.2.13 on 2023-04-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0023_registoguia_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registoguia',
            old_name='transpote',
            new_name='transporte',
        ),
    ]
