# Generated by Django 3.2.13 on 2023-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0025_fechaentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechaentrega',
            name='estado',
            field=models.CharField(max_length=30, verbose_name='Esatdo fecha'),
        ),
    ]
