# Generated by Django 3.2.13 on 2023-05-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230322_0848'),
        ('etiquetado', '0026_alter_fechaentrega_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaentrega',
            name='estado_entrega',
            field=models.CharField(blank=True, max_length=30, verbose_name='Esatdo entrega'),
        ),
        migrations.AddField(
            model_name='fechaentrega',
            name='user_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_entrega', to='users.userperfil', verbose_name='User entrega'),
        ),
    ]
