# Generated by Django 3.2.13 on 2023-05-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0027_auto_20230530_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechaentrega',
            old_name='estado_entrega',
            new_name='est_entrega',
        ),
        migrations.RenameField(
            model_name='fechaentrega',
            old_name='user_entrega',
            new_name='reg_entrega',
        ),
    ]
