# Generated by Django 3.2.13 on 2023-08-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0025_product_n_personas'),
        ('mantenimiento', '0004_auto_20230830_1158'),
        ('etiquetado', '0029_productarmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructivoEtiquetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='instructivo-etiquetado', verbose_name='Foto')),
                ('observaciones', models.CharField(blank=True, max_length=150, verbose_name='observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.equipo', verbose_name='Equipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.product', verbose_name='Producto')),
            ],
        ),
    ]
