# Generated by Django 3.2.13 on 2023-09-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0030_instructivoetiquetado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetadoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pedido', models.CharField(blank=True, max_length=10, verbose_name='N°. Pedido')),
                ('product_id', models.CharField(blank=True, max_length=50, verbose_name='Product id')),
                ('unidades', models.IntegerField(blank=True, verbose_name='Unidades')),
            ],
        ),
    ]
