# Generated by Django 3.2.13 on 2024-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0032_estadoetiquetadostock'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='whatsapp',
            field=models.BooleanField(default=False, verbose_name='Whatsapp'),
        ),
    ]
