# Generated by Django 3.2.13 on 2024-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0034_alter_estadopicking_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopicking',
            name='whatsapp',
            field=models.BooleanField(blank=True, default='', verbose_name='Whatsapp'),
        ),
    ]
