# Generated by Django 3.2.13 on 2024-08-30 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etiquetado', '0037_anexodoc_anexoguia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anexodoc',
            old_name='trasnporte',
            new_name='transporte',
        ),
        migrations.RemoveField(
            model_name='anexoguia',
            name='numero_anexo',
        ),
        migrations.AlterField(
            model_name='anexoguia',
            name='bodega_nombre',
            field=models.CharField(choices=[('Andagoya', 'Andagoya'), ('Cerezos', 'Cerezos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anexoguia',
            name='estado',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anexoguia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
