# Generated by Django 3.2.25 on 2024-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0038_auto_20240830_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexoguia',
            name='estado',
            field=models.CharField(default='Incompleto', max_length=20),
        ),
    ]
