# Generated by Django 3.2.25 on 2024-11-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0039_alter_anexoguia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEtiquetadoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.CharField(max_length=10)),
            ],
        ),
    ]
