# Generated by Django 5.1.4 on 2025-01-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0040_addetiquetadopublico'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionAndagoya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.CharField(choices=[('CN4', 'CN4'), ('CN5', 'CN5'), ('CN6', 'CN6'), ('CN7', 'CN7')], max_length=10, verbose_name='Bodega')),
                ('pasillo', models.CharField(max_length=10, verbose_name='Pasillo/Bloque')),
                ('modulo', models.CharField(max_length=10, verbose_name='ModuloPalet')),
                ('nivel', models.CharField(max_length=10, verbose_name='Nivel')),
                ('estanteria', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='ID del Producto')),
                ('ubicaciones', models.ManyToManyField(related_name='productos', to='etiquetado.ubicacionandagoya', verbose_name='Ubicaciones')),
            ],
        ),
    ]
