# Generated by Django 5.1.4 on 2025-01-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0041_ubicacionandagoya_productoubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='bodega',
            field=models.CharField(choices=[('AN1', 'AN1'), ('AN4', 'AN4'), ('BN1', 'BN1'), ('BN2', 'BN2'), ('BN3', 'BN3'), ('BN4', 'BN4')], max_length=10, verbose_name='Bodega'),
        ),
    ]
