# Generated by Django 5.1.4 on 2025-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0044_alter_ubicacionandagoya_modulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='modulo',
            field=models.CharField(blank=True, default='1', max_length=10, verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='pasillo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=10, verbose_name='Pasillo/Bloque'),
        ),
    ]
