# Generated by Django 5.1.4 on 2025-01-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0045_alter_ubicacionandagoya_modulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='modulo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Modulo'),
        ),
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='nivel',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nivel'),
        ),
    ]
