# Generated by Django 5.1.4 on 2025-01-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0046_alter_ubicacionandagoya_modulo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacionandagoya',
            unique_together={('bodega', 'pasillo', 'modulo')},
        ),
    ]
