# Generated by Django 5.1.4 on 2025-01-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0047_alter_ubicacionandagoya_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacionandagoya',
            unique_together={('bodega', 'pasillo', 'modulo', 'nivel')},
        ),
    ]
