# Generated by Django 5.1.4 on 2025-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0048_alter_ubicacionandagoya_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionandagoya',
            name='pasillo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=10, verbose_name='Pasillo/Bloque'),
        ),
    ]
