# Generated by Django 5.1.4 on 2025-02-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0050_productospedidotemporal_pedidotemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidotemporal',
            name='productos',
            field=models.ManyToManyField(blank=True, to='etiquetado.productospedidotemporal'),
        ),
    ]
