# Generated by Django 5.1.4 on 2025-02-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0051_alter_pedidotemporal_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidotemporal',
            old_name='user',
            new_name='usuario',
        ),
    ]
