# Generated by Django 5.1.4 on 2025-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0052_rename_user_pedidotemporal_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='foto_picking',
            field=models.ImageField(blank=True, null=True, upload_to='picking'),
        ),
    ]
