# Generated by Django 5.1.4 on 2025-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0053_estadopicking_foto_picking'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='foto_picking_2',
            field=models.ImageField(blank=True, null=True, upload_to='picking'),
        ),
    ]
