# Generated by Django 5.1.4 on 2025-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0054_estadopicking_foto_picking_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_id', models.CharField(max_length=20)),
                ('codigo_cliente', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('ware_code', models.CharField(max_length=5)),
                ('confimed', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField()),
                ('sec_name_cliente', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
