# Generated by Django 5.1.4 on 2025-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0055_reservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='reservas',
            name='fecha_pedido',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservas',
            name='hora_llegada',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='contrato_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='product_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='ware_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
