# Generated by Django 5.1.4 on 2025-04-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0056_remove_reservas_fecha_hora_reservas_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='confimed',
            new_name='confirmed',
        ),
    ]
