# Generated by Django 5.1.4 on 2025-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0057_rename_confimed_reservas_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='alterado',
            field=models.BooleanField(default=False),
        ),
    ]
