# Generated by Django 5.1.4 on 2025-04-24 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0058_reservas_alterado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
