# Generated by Django 5.1.4 on 2025-04-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0036_alter_product_unidad_empaque_and_more'),
        ('etiquetado', '0059_reservas_creado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosTransfCerAnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('lote_id', models.CharField(max_length=50)),
                ('fecha_caducidad', models.DateField()),
                ('cartones', models.IntegerField(default=0)),
                ('saldos', models.IntegerField(default=0)),
                ('unidades', models.IntegerField(default=0)),
                ('reservas', models.IntegerField(default=0)),
                ('detalle', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransfCerAnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('volumen_total', models.FloatField(null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='etiquetado.productostransfcerand')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.vehiculos')),
            ],
        ),
    ]
