# Generated by Django 5.1.4 on 2025-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0061_productostransfcerand_volumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostransfcerand',
            name='bodega',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productostransfcerand',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transfcerand',
            name='peso_total',
            field=models.FloatField(null=True),
        ),
    ]
