# Generated by Django 5.1.4 on 2025-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0062_productostransfcerand_bodega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfcerand',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transfcerand',
            name='peso_total',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='transfcerand',
            name='productos',
            field=models.ManyToManyField(blank=True, to='etiquetado.productostransfcerand'),
        ),
        migrations.AlterField(
            model_name='transfcerand',
            name='volumen_total',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
