# Generated by Django 5.1.4 on 2025-05-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0063_transfcerand_email_alter_transfcerand_peso_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
