# Generated by Django 5.1.4 on 2025-08-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0064_delete_reservas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfcerand',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='transfcerand',
            name='vehiculo',
        ),
        migrations.DeleteModel(
            name='ProductosTransfCerAnd',
        ),
        migrations.DeleteModel(
            name='TransfCerAnd',
        ),
    ]
