# Generated by Django 5.1.4 on 2025-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0065_remove_transfcerand_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='noti_errors',
            field=models.TextField(blank=True),
        ),
    ]
