# Generated by Django 5.1.4 on 2025-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0066_estadopicking_noti_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='noti_detalles',
            field=models.TextField(blank=True),
        ),
    ]
