# Generated by Django 5.1.4 on 2025-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0067_estadopicking_noti_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='n_factura',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
