# Generated by Django 5.1.4 on 2025-09-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0068_estadopicking_n_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='noti_email',
            field=models.TextField(blank=True),
        ),
    ]
