# Generated by Django 5.1.4 on 2025-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetado', '0069_estadopicking_noti_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopicking',
            name='email_picking_errors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estadopicking',
            name='email_picking_fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadopicking',
            name='email_picking_send',
            field=models.BooleanField(default=False),
        ),
    ]
